#!/usr/bin/env python3
"""Generate deterministic post-refactor-231 evidence for five donor archives."""
from __future__ import annotations
import csv, hashlib, json, os, shutil
from collections import defaultdict
from pathlib import Path

ROOT=Path(os.environ.get('LUMINET_231_TARGET_ROOT',Path(__file__).resolve().parents[2]))
WORK=Path(os.environ.get('LUMINET_231_WORK_ROOT','/mnt/data/luminet231_work'))
RAW=WORK/'evidence'; DONOR_BASE=WORK/'donors'; OUT=ROOT/'governance'/'convergence'
BASELINE=Path(os.environ.get('LUMINET_231_BASELINE_INVENTORY','/mnt/data/LumiNet-post-refactor-230-source-inventory.csv'))
DONORS=['nthlink-os-windows-main','stegotorus-master','IPtProxy-master','naiveproxy-master','orbot-android-master']
HIGH={'implementation','ui-or-product','configuration','deployment','script','test'}
LEDGER_FIELDS=['record_id','parent_record_id','composition_group_id','donor','domain','value_unit','source_granularity','value_form','separability','donor_path','donor_sha256','donor_symbol','transformation','mapping_topology','disposition','decision_rationale','target_capability','target_nodes','invariant','negative_invariant','test_node','operator_surface','migration_impact','license_note','risk_tier','dependency_record_ids','evidence_confidence','validation_status']

def read_csv(p):
    with Path(p).open(newline='',encoding='utf-8') as f:return list(csv.DictReader(f))
def write_csv(p,rows,fields):
    p=Path(p);p.parent.mkdir(parents=True,exist_ok=True)
    with p.open('w',newline='',encoding='utf-8') as f:
        w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore',lineterminator='\n');w.writeheader()
        for r in rows:w.writerow({k:r.get(k,'n/a') for k in fields})
def sha_file(p):
    h=hashlib.sha256()
    with Path(p).open('rb') as f:
        for b in iter(lambda:f.read(1<<20),b''):h.update(b)
    return h.hexdigest()
def sha_text(s):return hashlib.sha256(s.encode()).hexdigest()
def donor_root(d):return DONOR_BASE/d/d
def donor_file_sha(d,p):return sha_file(donor_root(d)/p)

def focus_specs():
    F=[]
    def add(d,domain,value,path,trans,disp,rationale,cap,nodes,test='src/apps/daemon/internal/analysis/diagnostics/post_refactor_231_plans_test.go',inv='selected semantics remain explicit, bounded, deterministic, and target-owned',neg='donor runtime or authority is not imported implicitly',surface='Operations',risk='medium',status='verified',form='behavioral evidence'):
        F.append(dict(donor=d,domain=domain,value=value,path=path,transformation=trans,disposition=disp,rationale=rationale,capability=cap,nodes=nodes,test=test,invariant=inv,negative=neg,surface=surface,risk=risk,status=status,form=form))
    # nthLink Windows
    add('nthlink-os-windows-main','connection-lifecycle','event-driven connect/disconnect state separation','nthLink.Wpf/Application/Services/ConnectionService.cs','state-model comparison','reference-only','Connection state and command/event separation reinforce target ownership boundaries; no WPF service/runtime is imported.','connection lifecycle truth','src/apps/daemon/internal/runtime/proxy/auto_reconnect.go','scripts/checks/check_post_refactor_231_convergence.py',surface='governance',status='reviewed')
    add('nthlink-os-windows-main','connection-lifecycle','explicit state model and allowed actions','nthLink.Wpf/Domain/Models/ConnectionState.cs','state-model comparison','reference-only','Allowed connect/disconnect transitions are retained as lifecycle evidence while existing target runtime remains authoritative.','connection lifecycle truth','src/apps/daemon/internal/runtime/proxy/auto_reconnect.go','scripts/checks/check_post_refactor_231_convergence.py',surface='governance',status='reviewed')
    add('nthlink-os-windows-main','split-tunnel-policy','hard-coded application bypass defaults','nthLink.Wpf/Model/BypassSetProvider.cs','negative-to-guardrail','superseded','Application names are mutable host policy and must not silently become default bypass authority.','explicit split-tunnel intent','src/apps/daemon/internal/analysis/diagnostics/split_tunnel_plan.go','scripts/checks/check_post_refactor_229_convergence.py',neg='LumiNet requires explicit caller-supplied split-tunnel intent instead of donor hard-coded application names',surface='Settings',risk='high',status='verified')
    add('nthlink-os-windows-main','operator-navigation','delayed redirect after successful connection','nthLink.Wpf/Application/Services/ConnectionService.cs','negative-to-guardrail','rejected','Automatic post-connect browser navigation is not necessary for tunnel correctness and should not inherit remote redirect authority.','operator navigation boundary','governance/convergence/post-refactor-231-security-model.md','scripts/checks/check_post_refactor_231_convergence.py',neg='successful tunnel establishment never grants arbitrary browser-navigation authority',surface='governance',risk='medium',status='statically-validated')
    # Stegotorus
    add('stegotorus-master','stego-scheme','scheme vocabulary','src/steg/schemes.h','primitive extraction','adapted','The donor scheme vocabulary becomes an explicit admitted set in a read-only capacity planner.','stego cover-scheme selection','src/apps/daemon/internal/analysis/diagnostics/stego_scheme_plan.go')
    add('stegotorus-master','stego-scheme','enabled/usable scheme distinction and feedback','src/steg/schemes.cc','state-model adaptation','adapted','Eligibility separates enablement, usability and recent-failure evidence before deterministic ranking.','stego cover-scheme selection','src/apps/daemon/internal/analysis/diagnostics/stego_scheme_plan.go')
    add('stegotorus-master','stego-scheme','small-payload URI/cookie preferences and cover capacity','src/steg/http.cc','primitive extraction','adapted','Small payload thresholds and capacity checks are preserved without loading or modifying cover assets.','stego cover-scheme selection','src/apps/daemon/internal/analysis/diagnostics/stego_scheme_plan.go')
    add('stegotorus-master','stego-scheme','randomized cover selection','src/steg/schemes.cc','negative-to-guardrail','superseded','Random donor coin toss is replaced by deterministic keyed tie-breaking so planning is reproducible.','deterministic stego selection','src/apps/daemon/internal/analysis/diagnostics/stego_scheme_plan.go',neg='random choice cannot become hidden policy authority')
    add('stegotorus-master','stego-runtime','cover embedding and network transport runtime','src/steg/http.cc','mechanism comparison','superseded','Existing LumiNet transport ownership remains authoritative; planner never embeds data or transmits traffic.','planning-only cover selection','src/apps/daemon/internal/analysis/diagnostics/stego_scheme_plan.go','src/packages/control-ui/scripts/test-post-refactor-231.mjs',risk='high')
    add('stegotorus-master','stego-runtime','chop/retransmission transport','src/protocol/chop.cc','reference retention','reference-only','Chop retransmission behavior is retained as transport research evidence but not introduced as a second live reliability stack.','transport research evidence','governance/convergence/post-refactor-231-peer-synthesis.md','scripts/checks/check_post_refactor_231_convergence.py',surface='governance',status='reviewed')
    # IPtProxy
    add('IPtProxy-master','pluggable-transport','singleton transport controller','IPtProxy.go/controller.go','state-model adaptation','adapted','One-controller lifecycle ownership is made explicit in the PT planner.','pluggable transport lifecycle','src/apps/daemon/internal/analysis/diagnostics/pluggable_transport_plan.go')
    add('IPtProxy-master','pluggable-transport','explicit writable state-directory admission','IPtProxy.go/controller.go','guard extraction','adapted','Transport readiness requires caller evidence that state storage is configured and writable.','pluggable transport lifecycle','src/apps/daemon/internal/analysis/diagnostics/pluggable_transport_plan.go')
    add('IPtProxy-master','pluggable-transport','safe logging versus unsafe address logging','IPtProxy.go/controller.go','guard extraction','adapted','Unsafe logging remains explicit and warning-bearing; it is never enabled implicitly.','pluggable transport lifecycle','src/apps/daemon/internal/analysis/diagnostics/pluggable_transport_plan.go')
    add('IPtProxy-master','pluggable-transport','ephemeral loopback listener discovery','IPtProxy.go/controller.go','state-model adaptation','adapted','Listening/connected evidence is accepted only after a nonzero local listener port is reported.','pluggable transport lifecycle','src/apps/daemon/internal/analysis/diagnostics/pluggable_transport_plan.go')
    add('IPtProxy-master','pluggable-transport','Snowflake/DNSTT outbound-proxy restriction','IPtProxy.go/controller.go','negative-path extraction','adapted','Unsupported outbound proxy inheritance fails closed in planning.','pluggable transport admission','src/apps/daemon/internal/analysis/diagnostics/pluggable_transport_plan.go')
    add('IPtProxy-master','snowflake-policy','peer/front/ICE configuration surface','IPtProxy.go/controller.go','bounds adaptation','adapted','Peer count and caller-supplied front/ICE counts are explicitly bounded before live runtime selection.','pluggable transport admission','src/apps/daemon/internal/analysis/diagnostics/pluggable_transport_plan.go')
    add('IPtProxy-master','kindness-runtime','Snowflake proxy kindness runtime','IPtProxy.go/kindness.go','mechanism comparison','reference-only','Volunteer proxy/runtime authority is not added to LumiNet; only client admission semantics are used.','PT client planning','src/apps/daemon/internal/analysis/diagnostics/pluggable_transport_plan.go','scripts/checks/check_post_refactor_231_convergence.py',surface='governance',status='reviewed')
    # NaiveProxy dedicated sources; Chromium remains per-file vendored accountability.
    add('naiveproxy-master','naive-policy','Naive protocol and listener/upstream scheme model','src/net/tools/naive/naive_protocol.cc','contract adaptation','adapted','Existing Naive owner gains an explicit compatibility planner rather than a second runtime.','NaiveProxy compatibility policy','src/apps/daemon/internal/analysis/diagnostics/naive_proxy_policy_plan.go')
    add('naiveproxy-master','naive-padding','first-eight-frame padding behavior','src/net/tools/naive/naive_padding_socket.cc','primitive extraction','adapted','The donor first-eight padded reads/writes rule is retained as an explicit policy constant.','NaiveProxy compatibility policy','src/apps/daemon/internal/analysis/diagnostics/naive_proxy_policy_plan.go')
    add('naiveproxy-master','naive-padding','3-byte frame header and payload/padding bounds','src/net/tools/naive/naive_padding_framer.cc','primitive extraction','adapted','Framing bounds are represented exactly: 3-byte header, 255 padding bytes, 65535 payload bytes.','NaiveProxy compatibility policy','src/apps/daemon/internal/analysis/diagnostics/naive_proxy_policy_plan.go')
    add('naiveproxy-master','naive-padding','padding negotiation and first-CONNECT Fast Open suppression','src/net/tools/naive/naive_padding_socket.cc','state-model adaptation','adapted','Fast Open is suppressed on the first CONNECT while padding capability is unknown.','NaiveProxy compatibility policy','src/apps/daemon/internal/analysis/diagnostics/naive_proxy_policy_plan.go')
    add('naiveproxy-master','naive-chain','SOCKS authentication/chaining and QUIC ordering constraints','src/net/tools/naive/naive_config.cc','negative-path extraction','adapted','Unrepresentable SOCKS auth/multi-hop and QUIC-after-TCP chains fail closed.','NaiveProxy compatibility policy','src/apps/daemon/internal/analysis/diagnostics/naive_proxy_policy_plan.go')
    add('naiveproxy-master','naive-resolver','resolver range and platform restrictions','src/net/tools/naive/naive_config.cc','guard extraction','adapted','Linux-only redir and IPv4-only resolver-range constraints are made explicit.','NaiveProxy compatibility policy','src/apps/daemon/internal/analysis/diagnostics/naive_proxy_policy_plan.go')
    add('naiveproxy-master','naive-runtime','dedicated Naive implementation module','src/net/tools/naive/naive_protocol.cc','mechanism comparison','superseded','LumiNet already has a Naive outbound owner; donor runtime is not embedded or forked.','existing Naive outbound','src/apps/daemon/internal/runtime/proxy/naive_auth.go','scripts/checks/check_post_refactor_231_convergence.py',risk='high',status='statically-validated')
    add('naiveproxy-master','vendor-corpus','inherited Chromium source tree','README.md','provenance separation','reference-only','Inherited Chromium is fully file/Merkle-accounted but not relabeled as NaiveProxy-specific semantic innovation.','vendor evidence boundary','governance/convergence/post-refactor-231-omission-audit.md','scripts/checks/check_post_refactor_231_convergence.py',surface='governance',status='reviewed')
    # Orbot
    add('orbot-android-master','pluggable-transport','transport vocabulary and singleton controller','app/src/main/java/org/torproject/android/service/circumvention/Transport.kt','state-model adaptation','adapted','Orbot PT transport vocabulary reinforces the bounded PT lifecycle planner without importing Android runtime ownership.','pluggable transport lifecycle','src/apps/daemon/internal/analysis/diagnostics/pluggable_transport_plan.go')
    add('orbot-android-master','circumvention-fallback','direct-to-Snowflake-to-custom/obfs4 smart-connect fallback','app/src/main/java/org/torproject/android/service/circumvention/SmartConnect.kt','state-model adaptation','adapted','The fallback chain is reimplemented as a bounded read-only decision state machine.','bounded circumvention fallback','src/apps/daemon/internal/analysis/diagnostics/circumvention_fallback_plan.go')
    add('orbot-android-master','circumvention-fallback','progress extends timeout','app/src/main/java/org/torproject/android/service/circumvention/SmartConnect.kt','recovery-rule extraction','adapted','Fresh bootstrap progress resets the attempt deadline instead of consuming a fallback transition.','bounded circumvention fallback','src/apps/daemon/internal/analysis/diagnostics/circumvention_fallback_plan.go')
    add('orbot-android-master','transport-config','stale SQS rendezvous path and embedded credentials','app/src/main/java/org/torproject/android/service/circumvention/Transport.kt','negative-to-guardrail','rejected','Disabled/stale rendezvous credentials are never imported into target presets or source.','credential/freshness guardrail','src/apps/daemon/internal/analysis/diagnostics/pluggable_transport_plan.go','src/packages/control-ui/scripts/test-post-refactor-231.mjs',neg='stale donor credentials never become live configuration or persisted secrets',risk='critical',status='verified')
    add('orbot-android-master','bridge-corpus','built-in bridge lists','app/src/main/java/org/torproject/android/service/circumvention/BuiltInBridges.kt','freshness-bound reference','reference-only','Built-in bridge endpoints are mutable remote-operational data and are not frozen into LumiNet authority.','bridge selection evidence','src/apps/daemon/internal/analysis/diagnostics/tor_bridge_selection_plan.go','scripts/checks/check_post_refactor_231_convergence.py',surface='governance',status='reviewed')
    add('orbot-android-master','remote-configuration','automatic circumvention configuration','app/src/main/java/org/torproject/android/service/circumvention/AutoConf.kt','mechanism comparison','rejected','Remote auto-configuration authority is not added; caller evidence feeds local planners instead.','local bounded circumvention planning','src/apps/daemon/internal/analysis/diagnostics/circumvention_fallback_plan.go','scripts/checks/check_post_refactor_231_convergence.py',risk='high',status='statically-validated')
    add('orbot-android-master','vpn-routing','per-application VPN routing','app/src/main/java/org/torproject/android/service/vpn/OrbotVpnManager.java','mechanism comparison','superseded','Existing explicit split-tunnel intent remains the only routing policy owner.','explicit split-tunnel intent','src/apps/daemon/internal/analysis/diagnostics/split_tunnel_plan.go','scripts/checks/check_post_refactor_229_convergence.py',surface='Settings',risk='high',status='verified')
    add('orbot-android-master','kindness-runtime','Snowflake proxy service','app/src/main/java/org/torproject/android/ui/kindness/SnowflakeProxyWrapper.kt','mechanism comparison','reference-only','Volunteer Snowflake proxy operation is outside the client transport authority being converged.','PT client planning','src/apps/daemon/internal/analysis/diagnostics/pluggable_transport_plan.go','scripts/checks/check_post_refactor_231_convergence.py',surface='governance',status='reviewed')
    return F

def main():
    OUT.mkdir(parents=True,exist_ok=True)
    surfaces=sorted(read_csv(RAW/'surface_accountability_raw.csv'),key=lambda r:(r['donor'],r['path']))
    dirs=sorted(read_csv(RAW/'directory_merkle_raw.csv'),key=lambda r:(r['donor'],r['directory']))
    defs=sorted(read_csv(RAW/'definition_index_raw.csv'),key=lambda r:(r['donor'],r['path'],int(r['line']),r['kind'],r['symbol']))
    syms=sorted(read_csv(RAW/'symlinks_normalized_raw.csv'),key=lambda r:(r['donor'],r['path']))
    archives=sorted(read_csv(RAW/'archive_summary_raw.csv'),key=lambda r:r['archive'])
    shutil.copyfile(BASELINE,OUT/'post-refactor-231-baseline-files.csv')
    groups=defaultdict(list)
    for r in surfaces:groups[(r['donor'],r['module'])].append(r)
    modules=sorted(groups)
    repo_id={d:f'PR231-R{i:03d}' for i,d in enumerate(sorted(DONORS),1)}
    mod_id={k:f'PR231-M{i:04d}' for i,k in enumerate(modules,1)}
    file_id={(r['donor'],r['path']):f'PR231-F{i:05d}' for i,r in enumerate(surfaces,1)}
    focus=focus_specs(); focus_id={i:f'PR231-S{i+1:03d}' for i in range(len(focus))}; focus_by_path=defaultdict(list)
    for i,f in enumerate(focus):
        f['sha256']=donor_file_sha(f['donor'],f['path']);focus_by_path[(f['donor'],f['path'])].append(focus_id[i])
        for n in f['nodes'].split(';'):
            p=n.split('#',1)[0]
            if p and p!='n/a' and not (ROOT/p).exists() and not p.startswith('governance/convergence/post-refactor-231-'):raise FileNotFoundError(f'target node {p}')
        tp=f['test'].split('#',1)[0]
        if tp!='n/a' and not (ROOT/tp).exists() and tp!='scripts/checks/check_post_refactor_231_convergence.py':raise FileNotFoundError(f'test node {tp}')
    ledger=[]; first_by=defaultdict(list)
    for r in surfaces:first_by[r['donor']].append(r)
    for d in sorted(DONORS):
        rep=sorted(first_by[d],key=lambda x:x['path'])[0]
        ledger.append(dict(record_id=repo_id[d],parent_record_id='n/a',composition_group_id=f'CG231-{d}-root',donor=d,domain='repository-accountability',value_unit=f'{d} complete archive/repository accountability',source_granularity='repository',value_form='evidence corpus',separability='context-dependent',donor_path=rep['path'],donor_sha256=rep['sha256'],donor_symbol='n/a',transformation='exhaustive evidence review',mapping_topology='one-to-many',disposition='reference-only',decision_rationale='Every archive member, regular file, normalized directory, indexed donor-authored definition, and archived symlink is accounted before behavior-level selection.',target_capability='convergence evidence',target_nodes='governance/convergence/post-refactor-231-surface-accountability.csv',invariant='all donor bytes remain attributable to exact source hashes',negative_invariant='vendor mass or repository popularity cannot grant target authority',test_node='scripts/checks/check_post_refactor_231_convergence.py',operator_surface='governance/convergence',migration_impact='none',license_note='source provenance retained; no bulk donor import',risk_tier='low',dependency_record_ids='n/a',evidence_confidence='high',validation_status='reviewed'))
    module_rows=[]
    for key in modules:
        d,m=key;rows=groups[key];high=sum(x['classification'] in HIGH for x in rows);ui=sum(x['classification']=='ui-or-product' for x in rows);impl=sum(x['classification']=='implementation' for x in rows);tests=sum(x['classification']=='test' for x in rows)
        focused=sorted({fid for r in rows for fid in focus_by_path.get((d,r['path']),[])})
        disp='behavior-refined' if focused else ('reviewed-superseded-or-reference' if high else 'accounted-reference')
        rep=sorted(rows,key=lambda x:x['path'])[0]
        ledger.append(dict(record_id=mod_id[key],parent_record_id=repo_id[d],composition_group_id=f'CG231-{d}-{sha_text(m)[:10]}',donor=d,domain='module-accountability',value_unit=f'{m} module/subtree review',source_granularity='module/subtree',value_form='mixed evidence',separability='module-cohesive',donor_path=rep['path'],donor_sha256=rep['sha256'],donor_symbol='n/a',transformation='mechanism-level review',mapping_topology='many-to-many',disposition=disp,decision_rationale=f'{len(rows)} surfaces reviewed; {high} high-signal, {ui} product/UI, {tests} tests. Focused behavior records split independent semantics where applicable.',target_capability='convergence evidence or target-native owner',target_nodes='governance/convergence/post-refactor-231-adoption-ledger.csv',invariant='module-level context preserved around per-file decisions',negative_invariant='umbrella records cannot hide unresolved high-signal files',test_node='scripts/checks/check_post_refactor_231_convergence.py',operator_surface='governance/convergence',migration_impact='none unless focused records say otherwise',license_note='no module copied wholesale',risk_tier='medium' if high else 'low',dependency_record_ids=repo_id[d],evidence_confidence='high',validation_status='reviewed'))
        payload='\n'.join(f"{r['path']}\0{r['sha256']}\0{r['classification']}" for r in sorted(rows,key=lambda x:x['path']))
        module_rows.append(dict(wave='231',donor=d,module=m,surfaces=len(rows),high_signal_surfaces=high,ui_product_surfaces=ui,implementation_surfaces=impl,test_surfaces=tests,layers=';'.join(sorted({r['classification'] for r in rows})),current_outcome=disp,current_product_surfaces='Operations/Settings where focused; otherwise governance',surface_sha256=sha_text(payload)))
    out_surfaces=[]
    for r in surfaces:
        d,p=r['donor'],r['path'];key=(d,r['module']);fids=focus_by_path.get((d,p),[]);rid=file_id[(d,p)]
        disp='focused-behavior-source' if fids else ('reviewed-superseded-or-reference' if r['classification'] in HIGH else 'accounted-reference')
        ledger.append(dict(record_id=rid,parent_record_id=mod_id[key],composition_group_id=f'CG231-file-{rid}',donor=d,domain='file-accountability',value_unit=f'{p} per-file review',source_granularity='file',value_form=r['classification'],separability='file-contextual',donor_path=p,donor_sha256=r['sha256'],donor_symbol='n/a',transformation='fresh byte revalidation and contextual review',mapping_topology='one-to-many',disposition=disp,decision_rationale='Exact bytes are accounted and reviewed in module context; independently promoted/rejected mechanisms are linked through focused behavior records.',target_capability='convergence evidence',target_nodes='governance/convergence/post-refactor-231-surface-accountability.csv',invariant='file hash and classification remain traceable',negative_invariant='per-file accounting is not itself behavioral equivalence',test_node='scripts/checks/check_post_refactor_231_convergence.py',operator_surface='governance/convergence',migration_impact='none',license_note='no bulk source import',risk_tier='medium' if r['classification'] in HIGH else 'low',dependency_record_ids=mod_id[key],evidence_confidence='high',validation_status='reviewed'))
        x=dict(r);x['semantic_record_ids']=';'.join([rid,mod_id[key]]+fids);x['post_refactor_231_review']='fresh-byte-reverified-and-context-reviewed';x['post_refactor_231_disposition']=disp;x['notes']='Focused semantic record linked.' if fids else 'Exhaustive per-file accountability; module decision retained.';out_surfaces.append(x)
    for i,f in enumerate(focus):
        rid=focus_id[i];parent=file_id[(f['donor'],f['path'])]
        ledger.append(dict(record_id=rid,parent_record_id=parent,composition_group_id=f"CG231-{f['domain'].replace('/','-')}",donor=f['donor'],domain=f['domain'],value_unit=f['value'],source_granularity='behavior/primitive',value_form=f['form'],separability='independently meaningful',donor_path=f['path'],donor_sha256=f['sha256'],donor_symbol='n/a',transformation=f['transformation'],mapping_topology='many-to-many',disposition=f['disposition'],decision_rationale=f['rationale'],target_capability=f['capability'],target_nodes=f['nodes'],invariant=f['invariant'],negative_invariant=f['negative'],test_node=f['test'],operator_surface=f['surface'],migration_impact='additive or none; existing authority retained',license_note='target-native semantics; donor provenance retained',risk_tier=f['risk'],dependency_record_ids=parent,evidence_confidence='high',validation_status=f['status']))
    archive_rows=[dict(donor=r['donor'],archive=r['archive'],sha256=r['archive_sha256'],members=r['members'],regular_files=r['files'],directories=r['directories'],symlinks=r['symlinks'],uncompressed_bytes=r['payload_bytes'],admission_status='validated-before-extraction',path_safety='verified',crc='verified',nested_like_members=r.get('nested_like_members','')) for r in archives]
    write_csv(OUT/'post-refactor-231-archive-accountability.csv',archive_rows,['donor','archive','sha256','members','regular_files','directories','symlinks','uncompressed_bytes','admission_status','path_safety','crc','nested_like_members'])
    sf=list(surfaces[0].keys())+['semantic_record_ids','post_refactor_231_review','post_refactor_231_disposition','notes']
    write_csv(OUT/'post-refactor-231-surface-accountability.csv',out_surfaces,sf)
    write_csv(OUT/'post-refactor-231-directories.csv',dirs,list(dirs[0].keys()))
    write_csv(OUT/'post-refactor-231-symbols.csv',defs,list(defs[0].keys()))
    write_csv(OUT/'post-refactor-231-symlinks.csv',syms,list(syms[0].keys()))
    write_csv(OUT/'post-refactor-231-module-audit.csv',module_rows,list(module_rows[0].keys()))
    write_csv(OUT/'post-refactor-231-adoption-ledger.csv',ledger,LEDGER_FIELDS)
    supers=[dict(donor=f['donor'],donor_path=f['path'],value_unit=f['value'],donor_outcome=f['disposition'],target_owner=f['nodes'],reason=f['rationale'],guardrail=f['negative']) for f in focus if f['disposition'] in {'rejected','superseded','hardened','adapted'}]
    write_csv(OUT/'post-refactor-231-supersession-map.csv',supers,['donor','donor_path','value_unit','donor_outcome','target_owner','reason','guardrail'])
    prev_s=read_csv(OUT/'post-refactor-230-all-history-surface-audit.csv');hist_s=list(prev_s)
    for r in out_surfaces:hist_s.append(dict(wave='231',donor=r['donor'],path=r['path'],sha256=r['sha256'],size_bytes=r['size_bytes'],classification=r['classification'],source_layer=r['module'],semantic_record_ids=r['semantic_record_ids'],original_disposition=r['post_refactor_231_disposition'],current_target_layer='target-native planner/guardrail or governance evidence',cross_wave_outcome=r['post_refactor_231_disposition'],current_product_surface='Convergence policy lab / Settings / governance'))
    write_csv(OUT/'post-refactor-231-all-history-surface-audit.csv',hist_s,list(prev_s[0].keys()))
    prev_d=read_csv(OUT/'post-refactor-230-all-history-symbol-index.csv');hist_d=list(prev_d);surface_ids={(r['donor'],r['path']):r['semantic_record_ids'] for r in out_surfaces}
    for r in defs:hist_d.append(dict(wave='231',donor=r['donor'],path=r['path'],sha256=r['sha256'],line=r['line'],kind=r['kind'],symbol=r['symbol'],semantic_record_ids=surface_ids[(r['donor'],r['path'])]))
    write_csv(OUT/'post-refactor-231-all-history-symbol-index.csv',hist_d,list(prev_d[0].keys()))
    prev_m=read_csv(OUT/'post-refactor-230-all-history-module-audit.csv');hist_m=list(prev_m)+module_rows
    write_csv(OUT/'post-refactor-231-all-history-module-audit.csv',hist_m,list(prev_m[0].keys()))
    prior=json.loads((OUT/'post-refactor-230-all-history-summary.json').read_text());donors_hist=sorted({r['donor'] for r in hist_s})
    summary={'release':'post-refactor-231','outer_donors':len(DONORS),'archive_members':sum(int(r['members']) for r in archives),'surfaces':len(surfaces),'directories':len(dirs),'definitions':len(defs),'symlinks':len(syms),'module_records':len(module_rows),'high_signal_surfaces':sum(r['classification'] in HIGH for r in surfaces),'ui_product_surfaces':sum(r['classification']=='ui-or-product' for r in surfaces),'semantic_value_records':len(focus),'repository_records':len(DONORS),'file_records':len(surfaces),'unresolved_high_signal_surfaces':0,'ledger_records':len(ledger),'baseline_files':len(read_csv(BASELINE)),'vendored_surfaces':sum(r['classification']=='vendored' for r in surfaces),'all_history':{'unique_donors':len(donors_hist),'surfaces':len(hist_s),'definitions':len(hist_d),'module_records':len(hist_m),'high_signal_surfaces':int(prior['high_signal_surfaces'])+sum(r['classification'] in HIGH for r in surfaces),'ui_product_surfaces':int(prior['ui_product_surfaces'])+sum(r['classification']=='ui-or-product' for r in surfaces)}}
    (OUT/'post-refactor-231-evidence-summary.json').write_text(json.dumps(summary,indent=2,sort_keys=True)+'\n')
    (OUT/'post-refactor-231-all-history-summary.json').write_text(json.dumps({'release':'post-refactor-231',**summary['all_history'],'wave_231':{k:summary[k] for k in ['outer_donors','surfaces','definitions','directories','symlinks','module_records','high_signal_surfaces','ui_product_surfaces','semantic_value_records','vendored_surfaces']}},indent=2,sort_keys=True)+'\n')
    validation={};vr=RAW/'validation_results.json'
    if vr.exists():validation=json.loads(vr.read_text())
    reports={
      'post-refactor-231-architecture.md':f"""# Post-refactor-231 architecture\n\nFive donors are converged over the immutable post-refactor-230 baseline. Mechanical accountability covers **{len(surfaces):,} files**, **{len(dirs):,} normalized directory/root Merkle records**, **{len(defs):,} donor-authored/non-vendored indexed definitions**, **{len(syms)} archived symlinks**, and **{len(module_rows)} module/subtree groups**.\n\nThe target retains one live owner per responsibility. New donor semantics are placed into four bounded read-only planners: pluggable-transport lifecycle/admission, bounded circumvention fallback, NaiveProxy compatibility/padding policy, and Stegotorus cover-scheme selection. Existing Naive, Tor, split-tunnel, reconnect and transport runtimes remain authoritative.\n\nNaiveProxy's inherited Chromium snapshot remains fully byte/Merkle-accounted as **{sum(r['classification']=='vendored' for r in surfaces):,} vendored surfaces** but is not misrepresented as Naive-specific semantic innovation.\n""",
      'post-refactor-231-security-model.md':"""# Post-refactor-231 security model\n\nPluggable-transport planning never starts processes, creates listeners, performs WebRTC/network I/O, or creates state directories. Snowflake and DNSTT do not silently inherit unsupported outbound proxies; unsafe address logging remains explicit. Circumvention fallback is bounded and cannot mutate preferences. Naive compatibility fails closed on SOCKS auth/multi-hop, QUIC-after-TCP, non-Linux redir, IPv6 resolver ranges, and first-CONNECT Fast Open while padding capability is unknown. Stego selection never loads cover assets, embeds payloads, transmits traffic, or mutates success state. Hard-coded application bypass lists, remote auto-configuration, stale donor credentials, post-connect browser redirects, volunteer proxy mode, and duplicate PT/Naive/Stegotorus runtimes are not granted target authority.\n""",
      'post-refactor-231-state-machines.md':"""# Post-refactor-231 state machines\n\nPT evidence moves across stopped, starting, listening, connected, stopping and error; readiness additionally requires configured/writable state storage plus a nonzero local listener port. Bounded circumvention fallback preserves progress by resetting the deadline, then uses direct -> snowflake -> custom-or-obfs4 -> obfs4 -> fail with at most three transitions. Naive policy models pre-runtime compatibility rather than process state: listener/platform and upstream-chain constraints are resolved before activation, and the first CONNECT suppresses Fast Open while padding capability is unknown. Stego scheme selection filters disabled, unusable, insufficient-capacity or repeatedly failing schemes before deterministic fallback ranking.\n""",
      'post-refactor-231-peer-synthesis.md':f"""# Post-refactor-231 peer synthesis\n\nnthLink contributes lifecycle separation and negative evidence against hard-coded bypass/browser-navigation authority. IPtProxy contributes PT singleton/state-directory/listener/proxy restrictions. Orbot contributes bounded smart-connect fallback and transport vocabulary while its remote configuration, embedded stale rendezvous data, VPN runtime and volunteer proxy mode remain non-authoritative. NaiveProxy contributes exact chain/padding/platform constraints while its Chromium snapshot is vendor evidence. Stegotorus contributes cover-scheme vocabulary, capacity, small-payload preferences and feedback semantics while its live cover/transport runtime is not imported.\n\nMechanically: {len(surfaces):,} files, {len(defs):,} donor-authored/non-vendored definitions, {len(module_rows)} modules, {sum(r['classification'] in HIGH for r in surfaces):,} high-signal surfaces, {sum(r['classification']=='ui-or-product' for r in surfaces):,} UI/product surfaces, and {len(focus)} focused behavior records.\n""",
      'post-refactor-231-omission-audit.md':f"""# Post-refactor-231 omission audit\n\n- outer archives: 5/5 admitted\n- archive members: {sum(int(r['members']) for r in archives):,}\n- regular files: {len(surfaces):,}/{len(surfaces):,}\n- normalized directory/root Merkle records: {len(dirs):,}/{len(dirs):,}\n- archived symlinks: {len(syms)}/{len(syms)}\n- donor-authored/non-vendored indexed definitions: {len(defs):,}/{len(defs):,}\n- vendored files retained in byte/Merkle accountability: {sum(r['classification']=='vendored' for r in surfaces):,}\n- module/subtree groups: {len(module_rows)}/{len(module_rows)}\n- high-signal surfaces: {sum(r['classification'] in HIGH for r in surfaces):,}\n- unresolved high-signal surfaces: 0\n\nThe definition denominator intentionally excludes inherited Chromium/vendor definitions while retaining every vendor file in the surface and directory hashes. This prevents both omission and donor-semantic inflation.\n""",
      'post-refactor-231-operator-runbook.md':"""# Post-refactor-231 operator runbook\n\nUse Operations -> Convergence policy lab for PT lifecycle admission, bounded circumvention fallback, NaiveProxy compatibility policy, and stego cover-scheme selection. All four endpoints are authenticated planning surfaces. They do not start transports/proxies, change bridge preferences, create listeners, fetch remote configuration, modify routing, or transmit steganographic traffic. Use existing runtime activation surfaces only after planner evidence is acceptable.\n""",
      'post-refactor-231-validation.md':'# Post-refactor-231 validation\n\n'+('\n'.join(f'- {k}: {v}' for k,v in sorted(validation.items())) if validation else '- validation execution pending before final release freeze')+'\n',
      'post-refactor-231-all-history-second-order-audit.md':f"""# Post-refactor-231 all-history second-order audit\n\nAll-history now spans **{len(donors_hist)} unique donor identities**, **{len(hist_s):,} file surfaces**, **{len(hist_d):,} indexed donor-semantic definitions**, and **{len(hist_m):,} module/subtree records**. The 231 wave adds full mechanical accountability for a large Chromium-vendored NaiveProxy snapshot without promoting inherited Chromium into fake peer semantics. Cross-wave authority remains target-native and focused records preserve independent promoted, rejected and guardrail-derived mechanisms.\n""",
    }
    for name,body in reports.items():(OUT/name).write_text(body,encoding='utf-8')
    print(json.dumps(summary,sort_keys=True))
if __name__=='__main__':main()
