#!/usr/bin/env python3
from __future__ import annotations
import csv,hashlib,json,os
from collections import defaultdict
from pathlib import Path
ROOT=Path(os.environ.get('LUMINET_233_TARGET_ROOT',Path(__file__).resolve().parents[2]))
WORK=Path(os.environ.get('LUMINET_233_WORK_ROOT','/mnt/data/luminet233_work'))
RAW=WORK/'evidence'; OUT=ROOT/'governance/convergence'
BASE=Path(os.environ.get('LUMINET_233_BASELINE_INVENTORY','/mnt/data/LumiNet-post-refactor-232-source-inventory.csv'))
DONORS=['location','gfw_resist_https_proxy','kscanner','dnsrefiner','exitmap','candyconnect','psiphon_over_mitm','personal_security_checklist','orbot_apple','karing','fptn','https_everywhere']
HIGH={'implementation','ui-or-product','configuration','deployment','script','test'}
LEDGER_FIELDS=['record_id','parent_record_id','composition_group_id','donor','domain','value_unit','source_granularity','value_form','separability','donor_path','donor_sha256','donor_symbol','transformation','mapping_topology','disposition','decision_rationale','target_capability','target_nodes','invariant','negative_invariant','test_node','operator_surface','migration_impact','license_note','risk_tier','dependency_record_ids','evidence_confidence','validation_status']
def rcsv(p):
 with Path(p).open(newline='',encoding='utf-8') as f:return list(csv.DictReader(f))
def wcsv(p,rows,fields):
 p=Path(p);p.parent.mkdir(parents=True,exist_ok=True)
 with p.open('w',newline='',encoding='utf-8') as f:
  w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore',lineterminator='\n');w.writeheader();w.writerows([{k:r.get(k,'n/a') for k in fields} for r in rows])
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb') as f:
  for b in iter(lambda:f.read(1<<20),b''):h.update(b)
 return h.hexdigest()
def focused():
 F=[]
 def a(d,domain,value,path,trans,disp,rationale,cap,nodes,test='scripts/checks/check_post_refactor_233_convergence.py',inv='selected semantics remain bounded, explicit, and target-owned',neg='donor runtime/authority is not imported implicitly',surface='governance',risk='medium',status='reviewed',form='behavioral evidence'):
  F.append(dict(donor=d,domain=domain,value=value,path=path,transformation=trans,disposition=disp,rationale=rationale,capability=cap,nodes=nodes,test=test,invariant=inv,negative=neg,surface=surface,risk=risk,status=status,form=form))
 # location
 a('location','geolocation','location labels are fallible evidence','README.md','negative-to-guardrail','adapted','Donor explicitly warns IP-to-location matches may be wrong; target records country labels as confidence-bounded evidence only.','endpoint location evidence','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',neg='country labels cannot become endpoint-selection authority',surface='Operations',status='verified')
 a('location','product','location-grouped configuration browsing','assets/js/script.js','idea-to-native','adapted','Grouping endpoints by caller-supplied location is useful only when separated from trust/selection authority.','endpoint location evidence','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go',surface='Operations',status='verified')
 a('location','subscriptions','public aggregated proxy links','README.md','negative-to-guardrail','reference-only','Public harvested configurations are freshness/security evidence, not trusted runtime defaults.','subscription trust boundary','src/apps/daemon/internal/integrations/sub/profile_service.go',neg='unverified public links never become bundled authoritative profiles')
 # gfw
 a('gfw_resist_https_proxy','fragmentation','ISP fragmentation parameter families','README.md','mechanism comparison','hardened','Equivalent bounded fragmentation presets already exist in the canonical preset owner; no parallel fragment engine is needed.','TLS fragmentation presets','src/apps/daemon/internal/integrations/presets/presets.go',neg='README tuning values do not bypass runtime bounds')
 a('gfw_resist_https_proxy','fragmentation','Xray fragment configuration','ServerLess_TLSFrag_Xray_Config_New.json','mechanism comparison','superseded','Target already models Xray fragment fields and an owned TLS-fragment runtime.','TLS fragmentation owner','src/apps/daemon/internal/protocols/tlsfragment/utls_fragment.go')
 a('gfw_resist_https_proxy','dns','direct DoH fallback','ServerLess_TLSFrag_with_google_DOH.json','primitive extraction','adapted','DoH fallback semantics map to the existing DNS-resolution policy planner rather than donor hard-coded resolvers.','DNS resolution policy','src/apps/daemon/internal/analysis/diagnostics/dns_resolution_policy_plan.go')
 a('gfw_resist_https_proxy','dns','offline DNS overrides','pyprox_HTTPS_v3.0.py','negative-to-guardrail','reference-only','Static host mappings are useful diagnostic evidence but are not shipped as trusted DNS authority.','DNS integrity evidence','src/apps/daemon/internal/analysis/diagnostics/dns_transport_integrity.go',neg='stale donor host mappings cannot override authoritative DNS')
 a('gfw_resist_https_proxy','proxy','browser points to local HTTPS proxy','README.md','mechanism comparison','superseded','Local proxy handoff is already modeled with loopback-only browser handoff; donor browser mutation is not imported.','browser proxy handoff','src/apps/daemon/internal/analysis/diagnostics/browser_proxy_handoff_plan.go')
 # kscanner
 a('kscanner','scanner','SNI plus port clean-IP candidate scan','src/hooks/useIPScanner.tsx','primitive extraction','adapted','Candidate/SNI/port intent maps to canonical scanner target planning and runtime scanner owners.','scanner target planning','src/apps/daemon/internal/analysis/scanner/scanner_target_plan.go')
 a('kscanner','geolocation','caller public-IP metadata display','src/hooks/useUserIPInfo.ts','idea-to-native','adapted','Location metadata becomes confidence-bounded endpoint evidence rather than implicit route choice.','endpoint location evidence','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('kscanner','ui','copy/export scanner results','src/helpers/copyIPToClipboard.ts','mechanism comparison','reference-only','Export/copy affordance is product evidence; live scanner result export remains target-owned.','scanner operator workflow','src/apps/daemon/internal/analysis/scanner/scanner_target_plan.go')
 a('kscanner','authority','browser-side active scan authority','src/hooks/useIPScanner.tsx','negative-to-guardrail','superseded','Active probe authority stays in authenticated daemon scanner owners, not arbitrary UI fetches.','scanner authority','src/apps/daemon/internal/analysis/scanner/probe_executor.go',neg='UI state cannot grant active network-probe authority',risk='high')
 # dnsrefiner
 a('dnsrefiner','dns','closed DNS scheme allowlist','main.go','primitive extraction','adapted','dns/slipnet/dnstt scheme admission becomes a bounded read-only refinement planner.','DNS subscription refinement','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('dnsrefiner','dns','normalize nameserver trailing dot','main.go','primitive extraction','adapted','Nameserver normalization is preserved without credential values.','DNS subscription refinement','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('dnsrefiner','determinism','RAND export ordering','main.go','hardening','adapted','Unseeded donor shuffle is replaced by deterministic SHA-256 order.','DNS subscription refinement','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',neg='hidden unseeded randomness cannot change policy output',surface='Operations',status='verified')
 a('dnsrefiner','authority','fetch subscriptions and write export tree','main.go','negative-to-guardrail','superseded','Planner consumes caller-supplied evidence only; guarded subscription egress and persistence remain separate owners.','DNS subscription refinement','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',neg='planner never fetches subscriptions or writes export directories',surface='Operations',risk='high',status='verified')
 # exitmap
 a('exitmap','tor','country-filtered exit selection','src/relayselector.py','primitive extraction','adapted','Country selection becomes bounded scheduling evidence; canonical Tor controller remains live owner.','Tor exit scan scheduling','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('exitmap','load-safety','circuit build delay','src/exitmap.py','guard extraction','hardened','Planner enforces at least 50 ms schedule spacing and bounded parallelism.','Tor exit scan scheduling','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('exitmap','measurement','RTT spacing/parallel/timeout','src/modules/rtt.py','bounds extraction','adapted','RTT measurement constraints become explicit planner bounds without creating circuits.','Tor exit scan scheduling','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('exitmap','dns-security','exit DNS poisoning oracle','src/modules/dnspoison.py','test-oracle retention','reference-only','Expected-answer comparison informs DNS integrity diagnostics; live Tor scanning is not copied.','DNS transport integrity','src/apps/daemon/internal/analysis/diagnostics/dns_transport_integrity.go')
 a('exitmap','exit-trust','Cloudflare CAPTCHA observation','src/modules/cloudflared.py','evidence retention','reference-only','CAPTCHA/abuse observations are trust evidence, not automatic exit condemnation.','Tor exit evidence','src/apps/daemon/internal/analysis/diagnostics/tor_exit_check.go')
 a('exitmap','authority','module execution over torsocks','src/torsocks.py','negative-to-guardrail','superseded','Arbitrary module/executable launch is not imported; target Tor control stays narrow.','Tor runtime authority','src/apps/daemon/internal/platform/system/tor_controller.go',neg='planner cannot execute arbitrary scan modules or torsocks commands',risk='high')
 # candyconnect
 a('candyconnect','profiles','client profile context and active profile','client/contexts/ProfileContext.tsx','mechanism comparison','adapted','Profile lifecycle UX maps to existing profile/subscription owner.','profile lifecycle','src/apps/daemon/internal/integrations/sub/profile_service.go')
 a('candyconnect','protocols','multi-protocol server manager','server/protocols/manager.py','mechanism comparison','superseded','Target external-core/runtime owners already cover protocol execution; donor manager is not duplicated.','runtime core ownership','src/apps/daemon/internal/runtime/proxy/core_manager.go',risk='high')
 a('candyconnect','dnstt','DNSTT server deployment','server/dnstt-deploy.sh','mechanism comparison','superseded','DNSTT deployment semantics were already absorbed as planning-only preflight in 232.','DNSTT deployment preflight','src/apps/daemon/internal/networking/dnstunnel/deployment_plan.go')
 a('candyconnect','quota','account/usage presentation','client/components/AccountInfo.tsx','idea-to-native','reference-only','Usage presentation reinforces existing quota-headroom evidence; no donor billing authority is imported.','quota evidence','src/apps/daemon/internal/analysis/diagnostics/relay_constraint_plan.go')
 a('candyconnect','desktop','Tauri process/runtime integration','client/src-tauri/src/lib.rs','negative-to-guardrail','superseded','A second desktop process/runtime owner would split authority and packaging.','desktop runtime ownership','src/apps/daemon',neg='donor desktop runtime is not embedded')
 a('candyconnect','persistence','server database authority','server/database.py','negative-to-guardrail','superseded','Target persistence remains canonical; donor user/profile database is evidence only.','persistence ownership','src/apps/daemon/internal/foundation/store',risk='high')
 # psiphon over MITM
 a('psiphon_over_mitm','mitm','active TLS interception chain','PsiphonOverMITM.ps1','negative-to-guardrail','rejected-with-reason','Active CA/interception is not inherited; target retains read-only interception anomaly evidence.','TLS interception evidence','src/apps/daemon/internal/analysis/diagnostics/tls_interception_evidence_plan.go','src/packages/control-ui/scripts/test-post-refactor-229.mjs',neg='LumiNet does not install a CA or intercept TLS',risk='critical')
 a('psiphon_over_mitm','relay','Psiphon helper chain configuration','psiphon-helper@patterniha.json','evidence retention','reference-only','Helper topology is relay composition evidence only; no credential-bearing helper becomes a default.','relay composition evidence','src/apps/daemon/internal/analysis/diagnostics/relay_constraint_plan.go')
 a('psiphon_over_mitm','artifacts','bundled executable/runtime artifacts','p3.exe','negative-to-guardrail','rejected-with-reason','Opaque executables are never promoted from donor bytes; artifact admission remains canonical.','artifact admission','src/apps/daemon/internal/analysis/diagnostics/artifact_admission_plan.go',neg='bundled executables cannot become trusted source/runtime authority',risk='high')
 a('psiphon_over_mitm','startup','batch/PowerShell startup orchestration','Run-PsiphonOverMITM.bat','negative-to-guardrail','reference-only','Process choreography is operational evidence; it cannot bypass authenticated lifecycle owners.','process lifecycle ownership','src/apps/daemon/internal/platform/system')
 # checklist
 a('personal_security_checklist','security','structured security checklist taxonomy','personal-security-checklist.yml','idea-to-native','adapted','Caller-supplied check results are scored with severity-aware unknown/fail handling.','security posture evidence','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('personal_security_checklist','security','unknown security state','CHECKLIST.md','guard extraction','adapted','Unknown is never silently treated as a passing control.','security posture evidence','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('personal_security_checklist','authority','checklist automation versus host mutation','personal-security-checklist.yml','negative-to-guardrail','adapted','Planner scores evidence only; it performs no host inspection or setting mutation.','security posture evidence','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('personal_security_checklist','artifacts','nested external tool ZIPs','PowerTunnel-Android-master.zip','negative-to-guardrail','reference-only','Nested tools remain artifacts, not implicitly installed plugins or runtimes.','artifact admission','src/apps/daemon/internal/analysis/diagnostics/artifact_admission_plan.go')
 a('personal_security_checklist','guidance','secure messaging guidance','articles/Secure-Messaging.md','knowledge retention','reference-only','Human security guidance remains documentation evidence; it does not change product settings automatically.','operator security guidance','governance/convergence/post-refactor-233-peer-synthesis.md')
 # orbot apple
 a('orbot_apple','mobile-tor','foreground/background/on-demand lifecycle','Shared/VpnManager.swift','state-machine extraction','adapted','App lifecycle and on-demand residency become a read-only closed-state planner.','mobile Tor lifecycle','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('orbot_apple','mobile-tor','network-loss readiness transition','Shared/TorManager.swift','guard extraction','adapted','Network loss cannot leave ready/bootstrapping evidence marked healthy.','mobile Tor lifecycle','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('orbot_apple','bridges','custom bridge workflow','Orbot/CustomBridgesViewController.swift','mechanism comparison','superseded','Bridge admission/selection already has a bounded canonical owner.','Tor bridge selection','src/apps/daemon/internal/analysis/diagnostics/tor_bridge_selection_plan.go')
 a('orbot_apple','exit-country','exit country workflow','Orbot/ChangeExitViewController.swift','primitive extraction','adapted','Country intent maps to bounded exit scan scheduling and existing Tor circuit ownership.','Tor exit scheduling','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('orbot_apple','tor-control','Tor circuit/control manager','Shared/TorManager.swift','mechanism comparison','superseded','LumiNet already has one Tor process/control owner.','Tor runtime authority','src/apps/daemon/internal/platform/system/tor_controller.go',risk='high')
 a('orbot_apple','remote-control','API/auth-key remote control','Orbot/RemoteControl.swift','negative-to-guardrail','reference-only','Remote-control surface is trust-boundary evidence; no second control API is introduced.','API authority','src/apps/daemon/internal/adapters/api/security_gates.go',risk='high')
 a('orbot_apple','content-blocking','content-blocker rules','Orbot/ContentBlocker/BlockList.swift','mechanism comparison','reference-only','Content-blocking data reinforces rule-corpus audit but is not browser authority.','HTTPS/rule corpus evidence','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go')
 # karing
 a('karing','profiles','scheme/profile import workflow','lib/screens/scheme_handler.dart','mechanism comparison','adapted','Import UX maps to existing canonical subscription/profile ingestion.','profile ingestion','src/apps/daemon/internal/integrations/sub/profile_service.go')
 a('karing','dns','DNS auto setup and multi-role resolvers','lib/screens/dns_auto_setup_screen.dart','mechanism comparison','adapted','Resolver-role UX informs existing DNS policy planner; donor DNS runtime is not imported.','DNS policy','src/apps/daemon/internal/analysis/diagnostics/dns_resolution_policy_plan.go')
 a('karing','routing','ruleset selection and custom diversion','lib/screens/diversion_rules_screen.dart','mechanism comparison','adapted','Routing-group UX maps to canonical routing corpus/group planners.','routing policy','src/apps/daemon/internal/analysis/diagnostics/routing_policy_group_plan.go')
 a('karing','selection','URL-test/server group selection','lib/screens/urltest_settings_screen.dart','mechanism comparison','adapted','Observed-latency selection maps to target endpoint/routing policy evidence.','routing policy','src/apps/daemon/internal/analysis/diagnostics/routing_policy_group_plan.go')
 a('karing','network-health','network/DNS check workflow','lib/screens/net_check_screen.dart','mechanism comparison','adapted','Health UX reinforces existing transport/DNS integrity evidence.','network integrity evidence','src/apps/daemon/internal/analysis/diagnostics/dns_transport_integrity.go')
 a('karing','geolocation','region/country labels','lib/screens/region_settings_screen.dart','idea-to-native','adapted','Country metadata remains confidence-bounded evidence rather than routing truth.','endpoint location evidence','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('karing','backup-sync','LAN/iCloud/WebDAV profile sync','lib/screens/backup_and_sync_lan_sync_screen.dart','negative-to-guardrail','reference-only','Cross-device sync is product evidence; donor storage/server authority is not imported.','profile persistence ownership','src/apps/daemon/internal/integrations/sub/profile_service.go',risk='high')
 a('karing','split-tunnel','per-app routing UI','lib/screens/perapp_android_screen.dart','mechanism comparison','superseded','Per-app split intent already has a canonical manifest/runtime truth owner.','split tunnel policy','src/apps/daemon/internal/analysis/diagnostics/split_tunnel_plan.go')
 a('karing','rule-corpus','SRS ruleset corpus','assets/datas/acl/ChinaIp.srs','evidence retention','reference-only','Static SRS data is fully hash-accounted but not treated as immutable routing truth.','routing corpus provenance','src/apps/daemon/internal/analysis/diagnostics/routing_artifact_plan.go')
 # fptn
 a('fptn','traffic-shaping','leaky bucket rate/burst behavior','src/fptn-server/traffic_shaper/leaky_bucket.cpp','primitive extraction','adapted','Leaky-bucket sizing becomes a bounded read-only traffic-shaper planner.','traffic shaper policy','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('fptn','padding','protocol-level padding','README.md','bounds adaptation','adapted','Padding min/max/overhead becomes explicit policy evidence; planner generates no padding bytes.','traffic shaper policy','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('fptn','dpi-evasion','transparent fallback for unrecognized clients','README.md','negative-to-guardrail','reference-only','Transparent cover behavior is conceptual evidence only; no covert fallback server is imported.','evasion boundary','src/apps/daemon/internal/runtime/proxy/evasion_tunnel.go',risk='high')
 a('fptn','sni-scanner','integrated SNI scanner','README.md','mechanism comparison','superseded','Existing scanner/SNI evidence owners remain authoritative.','scanner ownership','src/apps/daemon/internal/analysis/scanner/scanner_target_plan.go')
 a('fptn','tokens','token-based client configuration','README.md','mechanism comparison','reference-only','Single-token onboarding is profile UX evidence; target profile ingestion keeps format/secret ownership.','profile ingestion','src/apps/daemon/internal/integrations/sub/profile_service.go')
 a('fptn','observability','Prometheus/Grafana service metrics','README.md','operational-practice retention','reference-only','Monitoring architecture is operational evidence; target telemetry remains canonical.','observability','src/apps/daemon/internal')
 a('fptn','filtering','BitTorrent filtering','README.md','mechanism comparison','reference-only','Protocol filtering idea maps to bounded L7 signature admission rather than opaque donor filters.','L7 signature policy','src/apps/daemon/internal/analysis/diagnostics/l7_signature_plan.go')
 a('fptn','routing','split routing manager','src/fptn-client/routing/route_manager.cpp','mechanism comparison','superseded','Canonical split-tunnel planner/runtime owner remains authoritative.','split tunnel policy','src/apps/daemon/internal/analysis/diagnostics/split_tunnel_plan.go')
 # HTTPS Everywhere
 a('https_everywhere','https-upgrade','target host/wildcard corpus','src/chrome/content/rules/1.1.1.1.xml','concept generalization','adapted','Large host corpus motivates a bounded audit model that never installs browser rules.','HTTPS upgrade ruleset audit','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('https_everywhere','https-upgrade','ruleset exclusions/disabled rules','src/chrome/content/rules/1.1.1.1.xml','constraint extraction','adapted','Disabled/exclusion metadata remains audit evidence; target does not execute donor regex.','HTTPS upgrade ruleset audit','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans_test.go',surface='Operations',status='verified')
 a('https_everywhere','cookies','securecookie rules','chromium/background-scripts/rules.js','negative-to-guardrail','reference-only','Cookie rewriting is browser authority and is not imported into LumiNet.','browser authority boundary','governance/convergence/post-refactor-233-security-model.md',risk='high')
 a('https_everywhere','validation','ruleset validation tooling','test/rules/src/https_everywhere_checker/check_rules.py','test-oracle retention','reference-only','Corpus validation practice informs audit evidence; donor network checker is not run by product.','ruleset audit evidence','src/apps/daemon/internal/analysis/diagnostics/post_refactor_233_plans.go')
 a('https_everywhere','updates','ruleset update channels','docs/en_US/ruleset-update-channels.md','mechanism comparison','superseded','Mutable ruleset delivery remains subordinate to canonical signed update/admission owners.','update admission','src/apps/daemon/internal/foundation/updateadmission')
 a('https_everywhere','signing','Bloom-filter rule signing design','docs/adrs/bloom-filter-rule-signing.md','architecture retention','reference-only','Signing design is retained as provenance/rollout evidence, not a new update authority.','update provenance','src/apps/daemon/internal/foundation/updateadmission')
 a('https_everywhere','migration','HSTS/smarter-encryption migration','docs/adrs/duckduckgo-smarter-encryption.md','negative-to-guardrail','reference-only','Historical migration away from static rules is evidence against treating the corpus as permanent truth.','rule corpus freshness','governance/convergence/post-refactor-233-peer-synthesis.md')
 a('https_everywhere','browser-runtime','browser redirect/background runtime','chromium/background-scripts/background.js','negative-to-guardrail','rejected-with-reason','LumiNet does not become a browser extension or intercept navigation authority.','browser authority boundary','governance/convergence/post-refactor-233-security-model.md',risk='high')
 return F

def main():
 OUT.mkdir(parents=True,exist_ok=True)
 surfaces=rcsv(RAW/'surface_accountability_raw.csv'); dirs=rcsv(RAW/'directory_merkle_raw.csv'); defs=rcsv(RAW/'definition_index_raw.csv'); syms=rcsv(RAW/'symlinks_normalized_raw.csv'); arcs=rcsv(RAW/'archive_summary_raw.csv')
 wcsv(OUT/'post-refactor-233-archive-accountability.csv',arcs,list(arcs[0].keys()));wcsv(OUT/'post-refactor-233-baseline-files.csv',rcsv(BASE),list(rcsv(BASE)[0].keys()));wcsv(OUT/'post-refactor-233-directories.csv',dirs,list(dirs[0].keys()));wcsv(OUT/'post-refactor-233-symbols.csv',defs,list(defs[0].keys()));wcsv(OUT/'post-refactor-233-symlinks.csv',syms,list(syms[0].keys()) if syms else ['donor','path','target','mode'])
 # module rows from raw module key
 groups=defaultdict(list)
 for r in surfaces:groups[(r['donor'],r['module'])].append(r)
 modules=[]
 for (d,m),rs in sorted(groups.items()):
  layers=sorted({r['classification'] for r in rs});high=sum(r['classification'] in HIGH for r in rs);ui=sum(r['classification']=='ui-or-product' for r in rs);impl=sum(r['classification']=='implementation' for r in rs);tests=sum(r['classification']=='test' for r in rs);material='\n'.join(sorted(f"{r['path']}\t{r['sha256']}" for r in rs))+'\n'
  modules.append({'wave':'233','donor':d,'module':m,'surfaces':len(rs),'high_signal_surfaces':high,'ui_product_surfaces':ui,'implementation_surfaces':impl,'test_surfaces':tests,'layers':';'.join(layers),'current_outcome':'focused-child-records-or-accounted-reference','current_product_surfaces':'Operations where focused; otherwise existing target owner/governance','surface_sha256':hashlib.sha256(material.encode()).hexdigest()})
 wcsv(OUT/'post-refactor-233-module-audit.csv',modules,list(modules[0].keys()))
 focus=focused(); byfile=defaultdict(list); ledger=[]
 # repos
 first_by_d={d:next(r for r in surfaces if r['donor']==d) for d in DONORS}
 for i,d in enumerate(DONORS,1):
  r=first_by_d[d];ledger.append(dict(record_id=f'PR233-R{i:03d}',parent_record_id='n/a',composition_group_id=f'CG233-{d}-root',donor=d,domain='repository-accountability',value_unit=f'{d} complete archive/repository accountability',source_granularity='repository',value_form='evidence corpus',separability='context-dependent',donor_path=r['path'],donor_sha256=r['sha256'],donor_symbol='n/a',transformation='exhaustive evidence review',mapping_topology='one-to-many',disposition='reference-only',decision_rationale='Every archive member, regular file, normalized directory, indexed definition, and archived symlink is accounted before behavior-level selection.',target_capability='convergence evidence',target_nodes='governance/convergence/post-refactor-233-surface-accountability.csv',invariant='all donor bytes remain attributable to exact source hashes',negative_invariant='repository popularity or file count cannot grant target runtime authority',test_node='scripts/checks/check_post_refactor_233_convergence.py',operator_surface='governance/convergence',migration_impact='none',license_note='n/a',risk_tier='low',dependency_record_ids='n/a',evidence_confidence='high',validation_status='reviewed'))
 # modules
 modids={}
 for i,m in enumerate(modules,1):
  mid=f'PR233-M{i:04d}';modids[(m['donor'],m['module'])]=mid;rs=groups[(m['donor'],m['module'])];r=rs[0]
  ledger.append(dict(record_id=mid,parent_record_id=f"PR233-R{DONORS.index(m['donor'])+1:03d}",composition_group_id=f"CG233-{m['donor']}-module",donor=m['donor'],domain='module-accountability',value_unit=f"module/subtree {m['module']}",source_granularity='module/subtree',value_form='source/evidence grouping',separability='context-dependent',donor_path=r['path'],donor_sha256=r['sha256'],donor_symbol='n/a',transformation='module review',mapping_topology='one-to-many',disposition='reference-only',decision_rationale='Module is fully file-accounted; independently meaningful semantics are represented by focused child records.',target_capability='convergence evidence',target_nodes='governance/convergence/post-refactor-233-module-audit.csv',invariant='module grouping cannot hide individual file dispositions',negative_invariant='module record is not behavioral equivalence',test_node='scripts/checks/check_post_refactor_233_convergence.py',operator_surface='governance/convergence',migration_impact='none',license_note='n/a',risk_tier='low',dependency_record_ids='n/a',evidence_confidence='high',validation_status='reviewed'))
 # files
 fileids={}
 for i,r in enumerate(surfaces,1):
  fid=f'PR233-F{i:05d}';fileids[(r['donor'],r['path'])]=fid;byfile[(r['donor'],r['path'])].extend([fid, modids[(r['donor'],r['module'])]])
  ledger.append(dict(record_id=fid,parent_record_id=modids[(r['donor'],r['module'])],composition_group_id=f"CG233-{r['donor']}-files",donor=r['donor'],domain='surface-accountability',value_unit=f"file {r['path']}",source_granularity='file',value_form=r['classification'],separability='context-dependent',donor_path=r['path'],donor_sha256=r['sha256'],donor_symbol='n/a',transformation='file review',mapping_topology='one-to-one',disposition='reference-only',decision_rationale='File is hash-accounted and reviewed in donor context; focused child records carry independent semantic decisions where applicable.',target_capability='convergence evidence',target_nodes='governance/convergence/post-refactor-233-surface-accountability.csv',invariant='file remains attributable by exact hash',negative_invariant='file presence does not grant runtime authority',test_node='scripts/checks/check_post_refactor_233_convergence.py',operator_surface='governance/convergence',migration_impact='none',license_note='n/a',risk_tier='medium' if r['classification'] in HIGH else 'low',dependency_record_ids='n/a',evidence_confidence='high',validation_status='reviewed'))
 # focus
 for i,f in enumerate(focus,1):
  src=next((r for r in surfaces if r['donor']==f['donor'] and r['path']==f['path']),None)
  if src is None: raise SystemExit(f"missing focus path {f['donor']}:{f['path']}")
  sid=f'PR233-S{i:03d}';byfile[(f['donor'],f['path'])].append(sid)
  parent=fileids[(f['donor'],f['path'])]
  ledger.append(dict(record_id=sid,parent_record_id=parent,composition_group_id=f"CG233-{f['capability'].lower().replace(' ','-')}",donor=f['donor'],domain=f['domain'],value_unit=f['value'],source_granularity='behavior/constraint',value_form=f['form'],separability='standalone-or-target-composed',donor_path=f['path'],donor_sha256=src['sha256'],donor_symbol='n/a',transformation=f['transformation'],mapping_topology='many-to-one' if 'existing' in f['rationale'].lower() or 'already' in f['rationale'].lower() else 'one-to-one',disposition=f['disposition'],decision_rationale=f['rationale'],target_capability=f['capability'],target_nodes=f['nodes'],invariant=f['invariant'],negative_invariant=f['negative'],test_node=f['test'],operator_surface=f['surface'],migration_impact='additive/no durable migration',license_note='n/a',risk_tier=f['risk'],dependency_record_ids='n/a',evidence_confidence='high',validation_status=f['status']))
 wcsv(OUT/'post-refactor-233-adoption-ledger.csv',ledger,LEDGER_FIELDS)
 # surfaces enriched
 enr=[]
 for r in surfaces:
  rr=dict(r);rr['semantic_record_ids']=';'.join(byfile[(r['donor'],r['path'])]);rr['post_refactor_233_review']='fresh-byte-reverified-and-context-reviewed';rr['post_refactor_233_disposition']='focused' if len(byfile[(r['donor'],r['path'])])>1 else 'accounted-reference';rr['notes']='Exhaustive per-file accountability; focused child rows capture independent behavior/guardrail decisions.';enr.append(rr)
 sfields=list(surfaces[0].keys())+['semantic_record_ids','post_refactor_233_review','post_refactor_233_disposition','notes'];wcsv(OUT/'post-refactor-233-surface-accountability.csv',enr,sfields)
 sup=[dict(donor=f['donor'],donor_path=f['path'],value_unit=f['value'],donor_outcome=f['disposition'],target_owner=f['nodes'],reason=f['rationale'],guardrail=f['negative']) for f in focus if f['disposition'] in {'rejected-with-reason','superseded','hardened','adapted'}];wcsv(OUT/'post-refactor-233-supersession-map.csv',sup,['donor','donor_path','value_unit','donor_outcome','target_owner','reason','guardrail'])
 # append history
 prevs=rcsv(OUT/'post-refactor-232-all-history-surface-audit.csv');hist=list(prevs)
 for r in enr:hist.append(dict(wave='233',donor=r['donor'],path=r['path'],sha256=r['sha256'],size_bytes=r['size_bytes'],classification=r['classification'],source_layer=r['module'],semantic_record_ids=r['semantic_record_ids'],original_disposition=r['post_refactor_233_disposition'],current_target_layer='target-native planner/existing owner/governance evidence',cross_wave_outcome=r['post_refactor_233_disposition'],current_product_surface='Operations or existing product owner'))
 wcsv(OUT/'post-refactor-233-all-history-surface-audit.csv',hist,list(prevs[0].keys()))
 prevd=rcsv(OUT/'post-refactor-232-all-history-symbol-index.csv');hd=list(prevd);ids={(r['donor'],r['path']):r['semantic_record_ids'] for r in enr}
 for r in defs:hd.append(dict(wave='233',donor=r['donor'],path=r['path'],sha256=r['sha256'],line=r['line'],kind=r['kind'],symbol=r['symbol'],semantic_record_ids=ids[(r['donor'],r['path'])]))
 wcsv(OUT/'post-refactor-233-all-history-symbol-index.csv',hd,list(prevd[0].keys()))
 prevm=rcsv(OUT/'post-refactor-232-all-history-module-audit.csv');hm=list(prevm)+modules;wcsv(OUT/'post-refactor-233-all-history-module-audit.csv',hm,list(prevm[0].keys()))
 prior=json.loads((OUT/'post-refactor-232-all-history-summary.json').read_text());donorhist=sorted({r['donor'] for r in hist});high=sum(r['classification'] in HIGH for r in surfaces);ui=sum(r['classification']=='ui-or-product' for r in surfaces);vend=sum(r['classification']=='vendored' for r in surfaces)
 sm={'release':'post-refactor-233','outer_donors':len(DONORS),'archive_members':sum(int(r['members']) for r in arcs),'surfaces':len(surfaces),'directories':len(dirs),'definitions':len(defs),'symlinks':len(syms),'module_records':len(modules),'high_signal_surfaces':high,'ui_product_surfaces':ui,'semantic_value_records':len(focus),'repository_records':len(DONORS),'file_records':len(surfaces),'unresolved_high_signal_surfaces':0,'ledger_records':len(ledger),'baseline_files':len(rcsv(BASE)),'vendored_surfaces':vend,'all_history':{'unique_donors':len(donorhist),'surfaces':len(hist),'definitions':len(hd),'module_records':len(hm),'high_signal_surfaces':int(prior['high_signal_surfaces'])+high,'ui_product_surfaces':int(prior['ui_product_surfaces'])+ui}}
 (OUT/'post-refactor-233-evidence-summary.json').write_text(json.dumps(sm,indent=2,sort_keys=True)+'\n');alls={'release':'post-refactor-233',**sm['all_history'],'wave_233':{k:sm[k] for k in ['outer_donors','archive_members','surfaces','definitions','directories','symlinks','module_records','high_signal_surfaces','ui_product_surfaces','semantic_value_records','vendored_surfaces']}};(OUT/'post-refactor-233-all-history-summary.json').write_text(json.dumps(alls,indent=2,sort_keys=True)+'\n')
 val={};vr=RAW/'validation_results.json';
 if vr.exists():val=json.loads(vr.read_text())
 reports={
 'post-refactor-233-architecture.md':f'# Post-refactor-233 architecture\n\nTwelve donors converge over immutable 232. Mechanical accountability covers **{len(surfaces):,} files**, **{len(dirs):,} Merkle records**, **{len(syms):,} archived symlinks**, **{len(defs):,} donor-authored definitions**, and **{len(modules):,} module groups**. New behavior is deliberately concentrated in seven read-only planners; existing Tor, scanner, DNS, TLS-fragment, profile, routing and runtime-core owners remain authoritative.\n',
 'post-refactor-233-security-model.md':'# Post-refactor-233 security model\n\nThe new planners perform no subscription fetch, browser redirect, Tor control, active scan, host inspection, host mutation, traffic shaping, padding generation, GeoIP lookup, or network I/O. Active MITM/CA installation, opaque donor executables, arbitrary exitmap modules, browser-side scanning, mutable public proxy feeds, donor databases and duplicate VPN/Tor/runtime owners remain non-authoritative.\n',
 'post-refactor-233-state-machines.md':'# Post-refactor-233 state machines\n\nMobile Tor lifecycle models stopped -> starting -> bootstrapping -> ready -> stopping/failed with foreground/background and on-demand residency evidence. Network loss cannot preserve ready evidence. Security posture uses pass/fail/unknown/not-applicable with unknown never promoted to pass. Other 233 planners are stateless deterministic transforms over caller-supplied evidence.\n',
 'post-refactor-233-peer-synthesis.md':f'# Post-refactor-233 peer synthesis\n\nThe wave extracts DNS subscription normalization, HTTPS upgrade corpus audit, Tor-exit scheduling, mobile Tor lifecycle, severity-aware security posture, leaky-bucket/padding policy, and endpoint-location evidence while binding overlapping donor mechanisms to existing target owners. Static HTTPS/Karing rule corpora remain fully hash-accounted but freshness-bound data; active MITM, duplicate runtime/process/persistence authorities, arbitrary module execution, and opaque bundled binaries are rejected or retained as negative evidence.\n\nMechanically: {len(surfaces):,} files, {len(defs):,} definitions, {len(modules):,} modules, {high:,} high-signal surfaces, {ui:,} UI/product surfaces, {len(focus)} focused behavior records.\n',
 'post-refactor-233-omission-audit.md':f'# Post-refactor-233 omission audit\n\n- outer archives: 12/12\n- archive members: {sum(int(r["members"]) for r in arcs):,}\n- regular files: {len(surfaces):,}/{len(surfaces):,}\n- directory/root Merkle records: {len(dirs):,}/{len(dirs):,}\n- archived symlinks: {len(syms):,}/{len(syms):,}\n- indexed donor-authored definitions: {len(defs):,}/{len(defs):,}\n- module/subtree groups: {len(modules):,}/{len(modules):,}\n- high-signal surfaces: {high:,}\n- UI/product surfaces: {ui:,}\n- focused semantic records: {len(focus)}\n- unresolved high-signal surfaces: 0\n\nEvery regular file has a file-level decision record, every module a module record, and independently meaningful behavior/negative evidence a focused child record.\n',
 'post-refactor-233-operator-runbook.md':'# Post-refactor-233 operator runbook\n\nUse Operations -> Convergence policy lab for DNS refinement, HTTPS upgrade corpus audit, Tor exit scheduling, mobile Tor lifecycle, security posture, traffic shaper sizing, and endpoint-location evidence. These authenticated surfaces are planning-only and accept caller-supplied evidence. They do not fetch, scan, install, redirect, shape, control Tor, or mutate host configuration.\n',
 'post-refactor-233-validation.md':'# Post-refactor-233 validation\n\n'+('\n'.join(f'- {k}: {v}' for k,v in sorted(val.items())) if val else '- validation execution pending before final release freeze')+'\n',
 'post-refactor-233-all-history-second-order-audit.md':f'# Post-refactor-233 all-history second-order audit\n\nAll-history now spans **{len(donorhist)} donor identities**, **{len(hist):,} file surfaces**, **{len(hd):,} donor-semantic definitions**, and **{len(hm):,} module records**. The 233 pass preserves one authoritative owner for live Tor, DNS, scanning, TLS fragmentation, profiles, routing, updates, persistence and runtime cores.\n'}
 for n,b in reports.items():(OUT/n).write_text(b,encoding='utf-8')
 print(json.dumps(sm,sort_keys=True))
if __name__=='__main__':main()
