#!/usr/bin/env python3
from __future__ import annotations
import csv, hashlib, json, os, re, shutil, stat, zipfile
from collections import Counter, defaultdict
from pathlib import Path, PurePosixPath

ROOT = Path(os.environ.get('LUMINET_228_TARGET_ROOT', '/mnt/data/luminet228_work/target'))
E = ROOT / 'governance/convergence'
DONOR_BASE = Path(os.environ.get('LUMINET_228_DONOR_ROOT', '/mnt/data/luminet228_work/donors'))
INPUT226 = Path(os.environ.get('LUMINET_228_INPUT226', '/mnt/data/luminet226_inputs'))
SNI_ARCHIVE = Path(os.environ.get('LUMINET_228_SNI_ARCHIVE', '/mnt/data/sni-spoofing-rust-main.zip'))
BASELINE_INV = Path(os.environ.get('LUMINET_228_BASELINE_INVENTORY', '/mnt/data/LumiNet-post-refactor-227-source-inventory.csv'))

DONORS = {
    'shadowsocks-crypto': ('shadowsocks-crypto-main.zip', DONOR_BASE/'shadowsocks-crypto-main'/'shadowsocks-crypto-main'),
    'shadowsocksr': ('shadowsocksR-master.zip', DONOR_BASE/'shadowsocksR-master'/'shadowsocksR-master'),
    'shadowsocks-rust': ('shadowsocks-rust-master.zip', DONOR_BASE/'shadowsocks-rust-master'/'shadowsocks-rust-master'),
    'srsc': ('srsc-dev.zip', DONOR_BASE/'srsc-dev'/'srsc-dev'),
    'ssh': ('ssh-master.zip', DONOR_BASE/'ssh-master'/'ssh-master'),
    'subconverter': ('subconverter-master(1).zip', DONOR_BASE/'subconverter-master(1)'/'subconverter-master'),
    'tailscale-client': ('tailscale-client-go-main(3).zip', DONOR_BASE/'tailscale-client-go-main(3)'/'tailscale-client-go-main'),
    'tinytun': ('TinyTun-master(3).zip', DONOR_BASE/'TinyTun-master(3)'/'TinyTun-master'),
    'tools': ('Tools-main(3).zip', DONOR_BASE/'Tools-main(3)'/'Tools-main'),
    'browser-ext': ('ts-browser-ext-main(3).zip', DONOR_BASE/'ts-browser-ext-main(3)'/'ts-browser-ext-main'),
    'tsheadroom': ('tsheadroom-main(3).zip', DONOR_BASE/'tsheadroom-main(3)'/'tsheadroom-main'),
    'mwgp': ('mwgp-2.zip', DONOR_BASE/'mwgp-2'/'mwgp-2'),
    'paas-gateway': ('PaaS-vmess-trojan-argo-main.zip', DONOR_BASE/'PaaS-vmess-trojan-argo-main'/'PaaS-vmess-trojan-argo-main'),
    'reverse-tls': ('Reverse_tls-main.zip', DONOR_BASE/'Reverse_tls-main'/'Reverse_tls-main'),
    'sni-spoofing-rust': ('sni-spoofing-rust-main.zip', DONOR_BASE/'sni-spoofing-rust-main'/'sni-spoofing-rust-main'),
}

ARCHIVES = {d: (SNI_ARCHIVE if d == 'sni-spoofing-rust' else INPUT226/name) for d,(name,_) in DONORS.items()}

LEDGER_FIELDS = ['record_id','parent_record_id','composition_group_id','donor','domain','value_unit','source_granularity','value_form','separability','donor_path','donor_sha256','donor_symbol','transformation','mapping_topology','disposition','decision_rationale','target_capability','target_nodes','invariant','negative_invariant','test_node','operator_surface','migration_impact','license_note','risk_tier','dependency_record_ids','evidence_confidence','validation_status']

def sha_file(p: Path) -> str:
    h=hashlib.sha256()
    with p.open('rb') as f:
        for c in iter(lambda:f.read(1<<20),b''): h.update(c)
    return h.hexdigest()

def sha_bytes(b:bytes)->str:return hashlib.sha256(b).hexdigest()

def read_csv(p:Path):
    with p.open(newline='',encoding='utf-8') as f:return list(csv.DictReader(f))

def write_csv(p:Path, rows, fields):
    p.parent.mkdir(parents=True,exist_ok=True)
    with p.open('w',newline='',encoding='utf-8') as f:
        w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)

def norm(name:str)->PurePosixPath:
    if '\x00' in name: raise ValueError(f'NUL archive path: {name!r}')
    p=PurePosixPath(name.replace('\\','/'))
    if p.is_absolute() or any(x in ('','.','..') for x in p.parts) or (p.parts and ':' in p.parts[0]):
        raise ValueError(f'unsafe archive path: {name!r}')
    return p

# Exact predecessor evidence is the starting point, but all source bytes are rechecked.
s226=read_csv(E/'post-refactor-226-surface-accountability.csv')
s227=read_csv(E/'post-refactor-227-surface-accountability.csv')
pre_surfaces=s226+s227
surface_by={(r['donor'],r['path']):r for r in pre_surfaces}
if len(surface_by)!=1349: raise SystemExit(f'expected 1349 unique predecessor surfaces, got {len(surface_by)}')

# Archive admission and fresh extracted-byte equality for every donor file.
archive_rows=[]
for donor,(archive_name,root) in sorted(DONORS.items()):
    archive=ARCHIVES[donor]
    if not archive.is_file() or not root.is_dir(): raise SystemExit(f'missing donor input {donor}')
    with zipfile.ZipFile(archive) as z:
        if z.testzip() is not None: raise SystemExit(f'CRC failure {donor}')
        infos=z.infolist(); seen=set(); folded=set(); files=0; dirs=0; syms=0; total=0; roots=set()
        for info in infos:
            p=norm(info.filename); key=p.as_posix().rstrip('/'); roots.add(p.parts[0])
            if key in seen or key.casefold() in folded: raise SystemExit(f'duplicate/case collision {donor}:{key}')
            seen.add(key); folded.add(key.casefold()); total+=info.file_size
            mode=info.external_attr>>16; kind=stat.S_IFMT(mode)
            if kind not in (0,stat.S_IFREG,stat.S_IFDIR,stat.S_IFLNK): raise SystemExit(f'special archive member {donor}:{key}')
            if info.flag_bits&1: raise SystemExit(f'encrypted archive member {donor}:{key}')
            if info.is_dir(): dirs+=1; continue
            if kind==stat.S_IFLNK: syms+=1; continue
            files+=1
            rel=PurePosixPath(*p.parts[1:]).as_posix()
            row=surface_by.get((donor,rel))
            if row is None: raise SystemExit(f'archive file missing predecessor surface {donor}:{rel}')
            data=z.read(info); ah=sha_bytes(data); ph=sha_file(root/rel)
            if ah!=row['sha256'] or ph!=row['sha256']: raise SystemExit(f'byte mismatch {donor}:{rel}')
        if len(roots)!=1: raise SystemExit(f'{donor} archive root count {len(roots)}')
        archive_rows.append({'donor':donor,'archive':archive.name,'archive_sha256':sha_file(archive),'members':len(infos),'files':files,'directories':dirs,'symlinks':syms,'uncompressed_bytes':total,'validation':'CRC,path,duplicate,case,special,encryption,archive-vs-extracted-vs-predecessor-SHA verified'})

# Re-emit all 1,349 surfaces with a fresh-review envelope. No file disappears behind a module-level row.
surfaces=[]
for r in sorted(pre_surfaces,key=lambda x:(x['donor'],x['path'])):
    root=DONORS[r['donor']][1]; p=root/r['path']
    if not p.is_file(): raise SystemExit(f'missing extracted donor file {r["donor"]}:{r["path"]}')
    h=sha_file(p)
    if h!=r['sha256']: raise SystemExit(f'fresh donor hash mismatch {r["donor"]}:{r["path"]}')
    wave='226' if r['donor']!='sni-spoofing-rust' else '227'
    surfaces.append({**r,'predecessor_wave':wave,'post_refactor_228_review':'fresh-byte-reverified-and-semantic-row-revisited'})

# Recompute directory/root Merkle records directly from current extracted donors.
directories=[]
for donor,(_,root) in sorted(DONORS.items()):
    files=sorted([p for p in root.rglob('*') if p.is_file()],key=lambda p:p.relative_to(root).as_posix())
    dirs=[root]+sorted([p for p in root.rglob('*') if p.is_dir()],key=lambda p:p.relative_to(root).as_posix())
    for d in dirs:
        entries=[]
        for p in files:
            try: rel=p.relative_to(d).as_posix()
            except ValueError: continue
            entries.append((rel,sha_file(p)))
        payload=''.join(f'{h}  {rel}\n' for rel,h in entries).encode()
        directories.append({'donor':donor,'path':'.' if d==root else d.relative_to(root).as_posix(),'descendant_files':len(entries),'tree_sha256':sha_bytes(payload)})

# Definition accountability is preserved only after exact source-hash revalidation. Earlier extraction was also freshly rerun in 228 and matched byte-for-byte.
symbols=[]
for wave in (226,227):
    for r in read_csv(E/f'post-refactor-{wave}-symbols.csv'):
        donor=r['donor']; surface=surface_by[(donor,r['path'])]
        if r['sha256']!=surface['sha256'] or sha_file(DONORS[donor][1]/r['path'])!=r['sha256']:
            raise SystemExit(f'symbol source drift {donor}:{r["path"]}:{r["line"]}')
        symbols.append({**r,'predecessor_wave':str(wave),'post_refactor_228_review':'definition-index-reverified-on-identical-bytes'})

# All 949 predecessor semantic rows are explicitly revisited.
pre_ledger=[]
for wave in (226,227):
    for r in read_csv(E/f'post-refactor-{wave}-adoption-ledger.csv'):
        pre_ledger.append((wave,r))

# Refined second-order units. A path must be exact donor evidence unless this is a target-authority requirement row.
new_specs=[
 ('PR228-R001','n/a','CG228-all-donors','target-requirement','second-order-accountability','all 15 raw donor archives re-audited at archive/file/directory/definition/semantic levels','repository','evidence corpus','context-dependent','n/a','n/a','exhaustive successor audit','many-to-many','recomposed','The second-order pass rechecks the exact 949 predecessor decisions against unchanged donor bytes and separately records refined value units instead of inflating donor counts.','second-order convergence evidence','governance/convergence/post-refactor-228-second-order-review.csv','all 1,349 donor files and 16,310 definitions remain attributable while every predecessor semantic row receives an explicit 228 review status','large row counts alone cannot substitute for semantic review','scripts/checks/check_post_refactor_228_convergence.py#complete-re-review','governance/convergence','none','n/a','low','n/a','high','verified'),
 ('PR228-S001','PR228-R001','CG228-ssh-auth','ssh','ssh-auth','encrypted private-key passphrase admission','function + tests','authentication primitive','independently adoptable','keys.go','ParsePrivateKeyWithPassphrase','dependency-oracle extraction + target hardening','one-to-one','hardened','The donor dependency exposes passphrase-aware parsing; LumiNet now admits encrypted private keys without weakening its existing pinned host-key model.','SSH tunnel authentication admission','src/apps/daemon/internal/runtime/proxy/ssh_tunnel.go#buildAuthMethods','passphrase is accepted only with a private key and at least one valid auth method must exist before network I/O','orphan passphrases and invalid private-key-only auth cannot reach the network','src/apps/daemon/internal/runtime/proxy/ssh_tunnel_test.go#TestSSHTunnelEncryptedPrivateKeyPassphraseAdmission','Connections','additive optional credential field; password fallback preserved','predecessor provenance retained','high','PR228-R001','high','verified'),
 ('PR228-S002','PR228-S001','CG228-ssh-auth','ssh','ssh-secret-boundary','SSH key-passphrase secret redaction across evasion contract','cross-file contract','secret-handling invariant','independently adoptable','keys_test.go','PassphraseMissingError','target hardening','one-to-many','hardened','The new passphrase remains secret-bearing runtime state and is redacted/restored through the existing evasion contract sentinel rather than exposed as ordinary configuration.','evasion tunnel secret boundary','src/apps/daemon/internal/runtime/proxy/evasion_contract.go;src/apps/daemon/internal/runtime/proxy/evasion_tunnel.go','private-key passphrase never appears in redacted operator/evidence payloads','secret-bearing passphrases cannot cross the redacted contract or become an orphan credential','src/apps/daemon/internal/runtime/proxy/evasion_contract_test.go#TestRedactCovertTransportSecrets','Connections','additive redaction coverage','predecessor provenance retained','high','PR228-S001','high','verified'),
 ('PR228-RULE001','PR228-R001','CG228-routing-policy','subconverter','rules','extended local rule semantics: source CIDR/ports/process/GEOIP/rule-set/no-resolve','config + parser corpus','configuration semantics','independently adoptable','src/config/ruleset.h','n/a','bounded normalization rederivation','many-to-one','adapted','The converter corpus exposes independently useful rule types and trailing no-resolve semantics; LumiNet absorbs them into its offline local planner without remote fetching or installation.','local rule-set normalization','src/apps/daemon/internal/analysis/diagnostics/local_ruleset_plan.go#BuildLocalRuleSetPlan','rule parsing is bounded, deterministic, duplicate-aware, and local-only','unknown executable syntax, invalid ports/CIDRs, remote rule-set URLs, and implicit fetch/install fail closed','src/apps/daemon/internal/analysis/diagnostics/post_refactor_226_plans_test.go#TestPostRefactor228LocalRuleSetExtendedSemantics','Rules','additive preview grammar only','predecessor provenance retained','medium','PR228-R001','high','verified'),
 ('PR228-GROUP001','PR228-RULE001','CG228-routing-policy','subconverter','policy-groups','manual-select/url-test/fallback/load-balance group semantics','type + preset + generator','policy selection model','independently adoptable','src/config/proxygroup.h','ProxyGroupType','idea-to-native bounded planner','many-to-one','inspired-native','Select, url-test, fallback, and load-balance semantics become a read-only policy-group preview. Active url-test network probes are intentionally replaced by caller-supplied latency evidence.','routing policy-group planning','src/apps/daemon/internal/analysis/diagnostics/routing_policy_group_plan.go#BuildRoutingPolicyGroupPlan','automatic selection excludes unhealthy candidates and all limits/latency/weights are bounded','planner performs no probe, installs no policy, and cannot dispatch an unhealthy candidate automatically','src/apps/daemon/internal/analysis/diagnostics/post_refactor_226_plans_test.go#TestPostRefactor228RoutingPolicyGroupPlan','Rules','new non-authoritative planning endpoint/UI','predecessor provenance retained','medium','PR228-RULE001','high','verified'),
 ('PR228-GROUP002','PR228-GROUP001','CG228-routing-policy','subconverter','policy-group-presets','group preset structure without mutable remote corpus adoption','preset','preset semantics','independently adoptable','base/snippets/groups.toml','n/a','preset structure extraction','one-to-many','reference-only','Preset composition and group naming are useful design evidence, but the bundled domain/provider corpus is mutable/stale external policy and is not silently embedded as target truth.','policy preset provenance boundary','src/apps/daemon/internal/adapters/api/handlers_seventh_planners.go#GetConvergencePresets','preset modes are enumerated separately from mutable remote rule data','donor rule corpus never becomes authoritative target policy merely because it is large','scripts/checks/check_post_refactor_228_convergence.py#mutable-preset-boundary','Rules','no mutable donor corpus embedded','predecessor provenance retained','medium','PR228-GROUP001','high','reviewed'),
 ('PR228-B001','PR228-R001','CG228-browser-handoff','browser-ext','browser-native-host','browser family/extension identity/native host manifest contract','manifest + background + host','browser integration contract','independently adoptable','firefox/manifest.json','nativeMessaging','state-model rederivation','many-to-one','inspired-native','Chrome/Firefox native-messaging identity constraints and host allowlists are captured as a bounded manifest plan without registering a host.','browser/native-host proxy handoff','src/apps/daemon/internal/analysis/diagnostics/browser_proxy_handoff_plan.go#BuildBrowserProxyHandoffPlan','browser identity, allowed origins/extensions, commands, permissions, and 1 MiB message limit are explicit','planner cannot register a native host or grant wildcard browser authority','src/apps/daemon/internal/analysis/diagnostics/post_refactor_226_plans_test.go#TestPostRefactor228BrowserNativeHostContract','Settings','richer read-only plan','predecessor provenance retained','medium','PR228-R001','high','verified'),
 ('PR228-B002','PR228-B001','CG228-browser-handoff','browser-ext','browser-reconnect','native-message reconnect/backoff and loopback proxy bypass contract','background implementation','recovery + UX primitive','independently adoptable','background.js','n/a','bounded recovery extraction','one-to-one','inspired-native','Reconnect/backoff and loopback bypass behavior are retained as plan data while proxy authority stays in the browser/host owners.','browser companion recovery planning','src/apps/daemon/internal/analysis/diagnostics/browser_proxy_handoff_plan.go#BuildBrowserProxyHandoffPlan','reconnect backoff is finite and proxy target must be explicit loopback http/socks5 with no credentials/query/fragment','planner cannot mutate browser proxy state and cannot accept remote proxy targets','src/apps/daemon/internal/analysis/diagnostics/post_refactor_226_plans_test.go#TestPostRefactor228BrowserProxyHandoffRecovery','Settings','richer read-only plan','predecessor provenance retained','medium','PR228-B001','high','verified'),
 ('PR228-GW001','PR228-R001','CG228-gateway-topology','paas-gateway','gateway-presets','managed edge tunnel topology preset','deployment/config','topology pattern','independently adoptable','app.json','n/a','deployment-graph rederivation','many-to-one','recomposed','Managed edge tunnel composition becomes a target-native immutable graph preset; secret-bearing deployment/install steps are not imported.','gateway composition planning','src/apps/daemon/internal/analysis/diagnostics/gateway_composition_plan.go#BuildGatewayCompositionPlan','preset expands to a bounded acyclic service graph with topological start and reverse rollback order','planner downloads nothing and writes no systemd/cron/runit/Caddy/service configuration','src/apps/daemon/internal/analysis/diagnostics/post_refactor_226_plans_test.go#TestPostRefactor228GatewayPresets','Operations','new read-only presets','predecessor provenance retained','high','PR228-R001','high','verified'),
 ('PR228-GW002','PR228-GW001','CG228-gateway-topology','reverse-tls','gateway-presets','reverse TLS and websocket relay topology presets','deployment + documentation','topology pattern','independently adoptable','README.md','n/a','deployment-graph rederivation','many-to-one','recomposed','Reverse TLS/WS listener and relay roles become explicit service graph presets rather than a root-owned installer/runtime.','gateway composition planning','src/apps/daemon/internal/analysis/diagnostics/gateway_composition_plan.go#BuildGatewayCompositionPlan','reverse and websocket presets use the same DAG/restart/rollback invariants as explicit graphs','clone/build/systemd/root file-write behaviors cannot cross the planning boundary','src/apps/daemon/internal/analysis/diagnostics/post_refactor_226_plans_test.go#TestPostRefactor228GatewayPresets','Operations','new read-only presets','predecessor provenance retained','high','PR228-GW001','high','verified'),
 ('PR228-WG001','PR228-R001','CG228-wireguard-index','mwgp','wireguard-index','receiver-index translation recovery invariants','implementation + principles','state/recovery invariant','independently adoptable','wgit.go','n/a','mechanism extraction + negative guardrail','many-to-one','guardrail-derived','MWGP index translation reveals that mappings are identity/lifetime state and that live rewrites affect authenticated packet fields. LumiNet records the safe contract without becoming another WireGuard packet mutator.','WireGuard index translation planning','src/apps/daemon/internal/analysis/diagnostics/wireguard_index_translation_plan.go#BuildWireGuardIndexTranslationPlan','indexes are nonzero/unique, peer-bound, expire within 24h, and persisted mappings require post-restart revalidation','planner rewrites no packets/restores no mappings and translation never substitutes for WireGuard authentication/replay/cookie admission','src/apps/daemon/internal/analysis/diagnostics/post_refactor_226_plans_test.go#TestPostRefactor228WireGuardIndexTranslationPlan','Operations','new read-only recovery plan','predecessor provenance retained','high','PR228-R001','high','verified'),
 ('PR228-WG002','PR228-WG001','CG228-wireguard-index','mwgp','wireguard-obfuscation','obfuscation is traffic-shape modification only','documentation + implementation','negative invariant','independently adoptable','PRINCIPLES.md','n/a','negative-to-guardrail revalidation','many-to-one','guardrail-derived','The predecessor guardrail is retained after re-reading the full donor: packet obfuscation cannot be treated as authentication, confidentiality, replay protection, or cookie/MAC2 substitution.','WireGuard device policy','src/apps/daemon/internal/analysis/diagnostics/wireguard_device_policy_plan.go#BuildWireGuardDevicePolicyPlan','authentication and anti-replay remain WireGuard-owned','obfuscation cannot grant trust or bypass cryptographic admission','src/apps/daemon/internal/analysis/diagnostics/post_refactor_225_workflow_wireguard_test.go#TestPostRefactor226WireGuardReceiverIndexMappingsExpireAndBindSource','Operations','no runtime authority change','predecessor provenance retained','high','PR228-WG001','high','verified'),
 ('PR228-SS001','PR228-R001','CG228-shadowsocks-runtime','shadowsocks-rust','shadowsocks-plugin','SIP003 plugin intent preservation/fail-closed core compatibility','implementation + docs','protocol extension contract','independently adoptable','src/service/local.rs','plugin_opts','compatibility hardening','many-to-one','hardened','Parsed Shadowsocks plugin intent was preserved in share links but could be silently dropped by core generation. Supported sing-box internal plugins are now retained; unsupported plugin/prefix intent fails closed, and Xray refuses extensions it cannot represent.','Shadowsocks external-core compatibility','src/apps/daemon/internal/networking/proxyconfig/core_compat.go;src/apps/daemon/internal/runtime/proxy/core_manager.go','all parsed plugin/prefix semantics must either reach a compatible core config or fail before process start','core generation cannot silently erase SIP003 plugin/prefix intent','src/apps/daemon/internal/networking/proxyconfig/third_wave_contract_test.go#TestPostRefactor228ShadowsocksCoreCompatibilityPreservesOrRejectsExtensions','Profiles/Connections','hardens existing core generation','predecessor provenance retained','high','PR228-R001','high','verified'),
 ('PR228-SSR001','PR228-SS001','CG228-subscription-runtime-truth','shadowsocksr','subscription-runtime-truth','parsed protocol versus executable external-core truth','protocol/obfs implementation','product capability truth','independently adoptable','ssr/obfs.go','n/a','negative evidence to product guardrail','many-to-one','guardrail-derived','SSR remains parse/import compatibility evidence, not an executable maintained-core protocol. LumiNet now exposes that distinction before activation instead of presenting a late-failing action.','subscription node runtime capability','src/apps/daemon/internal/networking/proxyconfig/core_compat.go#EvaluateExternalCoreCompatibility;src/apps/daemon/internal/integrations/sub/node_catalogue.go#catalogueNodeView;src/packages/control-ui/src/pages/Profiles.tsx','credential-redacted node views expose whether any maintained external-core builder can represent the full config and which cores qualify','parsed/importable does not imply activatable; unsupported nodes cannot offer an enabled Activate SOCKS action','src/apps/daemon/internal/integrations/sub/node_catalogue_test.go#TestPostRefactor228NodeViewExposesRuntimeCompatibilityWithoutSecrets','Profiles','additive runtime-truth fields and UI state','predecessor provenance retained','high','PR228-SS001','high','verified'),
 ('PR228-SNI001','PR228-R001','CG228-sni-topology','sni-spoofing-rust','sni-self-loop','listener/upstream self-loop admission','configuration function','topology guard','independently adoptable','src/config.rs','connects_to_listener','negative-to-guardrail hardening','many-to-one','hardened','The donor explicitly rejects listener/upstream self-loops. LumiNet now checks declared literal endpoints offline, including loopback/unspecified same-port aliases, before treating a gateway plan as ready.','SNI gateway planning','src/apps/daemon/internal/analysis/diagnostics/sni_gateway_plan.go#BuildSNIGatewayPlan','declared listener/upstream endpoint pairs cannot resolve to a local self-loop','guard performs no DNS/network I/O and hostname inference cannot fabricate safety','src/apps/daemon/internal/analysis/diagnostics/post_refactor_225_test.go#TestPostRefactor228SNIGatewayRejectsDeclaredUpstreamSelfLoopOffline','Operations','adds offline topology guard','predecessor provenance retained','high','PR228-R001','high','verified'),
 ('PR228-SNI002','PR228-SNI001','CG228-sni-platform','sni-spoofing-rust','macos-bpf','macOS BPF raw-packet backend','implementation','platform capability evidence','independently reviewable','src/sniffer/macos.rs','BpfBackend','platform reference retention','one-to-one','reference-only','The donor contains a macOS BPF backend, but the target live raw injector still selects the unsupported stub on macOS and this environment cannot establish native parity. The gap stays explicit rather than being claimed by source inspection.','platform raw-packet capability','src/apps/daemon/internal/runtime/proxy/evasion_divert_stub.go','unsupported platforms remain visibly unsupported until native build/runtime evidence exists','donor source cannot grant a target platform-support claim','scripts/checks/check_post_refactor_228_convergence.py#macos-bpf-claim-boundary','Capabilities/Operations','no platform support claim','predecessor provenance retained','high','PR228-SNI001','high','reviewed'),
 ('PR228-WORK001','PR228-R001','CG228-worker-contract','tsheadroom','worker-protocol','ready handshake + correlated NDJSON framing','implementation + black-box tests','process protocol contract','independently adoptable','pool.go','requestEnvelope','protocol-contract rederivation','many-to-one','inspired-native','Worker protocol evidence becomes explicit planning invariants: one correlated request per NDJSON line, ready handshake before dispatch, bounded frame/readiness limits, and recycle on desynchronization.','worker affinity/recovery planning','src/apps/daemon/internal/analysis/diagnostics/worker_affinity_plan.go#BuildWorkerAffinityPlan','protocol framing, request correlation, frame cap, ready timeout, and recycle behavior are explicit and bounded','planner starts no worker and protocol desynchronization cannot be ignored','src/apps/daemon/internal/analysis/diagnostics/post_refactor_226_plans_test.go#TestPostRefactor228WorkerProtocolContractIsBoundedAndCorrelated','Health','richer read-only worker contract','predecessor provenance retained','medium','PR228-R001','high','verified'),
 ('PR228-WORK002','PR228-WORK001','CG228-worker-contract','tsheadroom','worker-affinity','depth-one affinity buffering and unbuffered spillover/backpressure','implementation + tests','concurrency/backpressure primitive','independently adoptable','pool_test.go','n/a','concurrency policy rederivation','many-to-one','inspired-native','The donor distinguishes one queued affinity job from unbuffered shared spillover. LumiNet records those queue semantics explicitly instead of implying generic buffering.','worker affinity/recovery planning','src/apps/daemon/internal/analysis/diagnostics/worker_affinity_plan.go#BuildWorkerAffinityPlan','affinity queue depth is one, shared spillover depth is zero, deterministic preference spills only to healthy capacity','planner cannot create an unbounded queue or assign unhealthy/saturated workers','src/apps/daemon/internal/analysis/diagnostics/post_refactor_226_plans_test.go#TestPostRefactor228WorkerProtocolContractIsBoundedAndCorrelated','Health','richer read-only worker contract','predecessor provenance retained','medium','PR228-WORK001','high','verified'),
 ('PR228-WORK003','PR228-WORK001','CG228-worker-contract','tsheadroom','worker-cancellation','fail-open cancellation / continue-to-warm / cold-first-call telemetry','worker implementation + tests','failure/recovery semantic','independently adoptable','worker.py','main','recovery policy rederivation','many-to-one','inspired-native','A cancelled caller may fail open while a bounded worker call continues to warm; protocol errors recycle the worker and cold-first-call behavior is telemetry-visible. These remain planning semantics, not process authority.','worker affinity/recovery planning','src/apps/daemon/internal/analysis/diagnostics/worker_affinity_plan.go#BuildWorkerAffinityPlan','caller cancellation, warming, recycle, deadlines, and restart backoff remain bounded and explicit','planner cannot spawn/restart a process or turn cancellation into unbounded background work','src/apps/daemon/internal/analysis/diagnostics/post_refactor_226_plans_test.go#TestPostRefactor228WorkerProtocolContractIsBoundedAndCorrelated','Health','richer read-only worker contract','predecessor provenance retained','medium','PR228-WORK001','high','verified'),
 ('PR228-TUN001','PR228-R001','CG228-platform-gap','tinytun','linux-process-attribution','Linux socket-to-process attribution via inet_diag + /proc inode ownership','implementation','platform capability mechanism','independently reviewable','src/process_lookup.rs','linux_find_pid','gap identification + explicit non-promotion','one-to-one','reference-only','The donor demonstrates a real Linux process-attribution mechanism while LumiCore currently returns an empty connection-owner list off Windows. Cargo/rustc are unavailable in this environment, so 228 records the gap rather than shipping an uncompiled native-path change.','cross-platform process attribution','src/packages/lumicore/src/netutil/supervision.rs#get_active_connections','platform support claims require compiled/native runtime evidence','source similarity cannot justify a Linux process-attribution support claim','scripts/checks/check_post_refactor_228_convergence.py#linux-process-attribution-gap','Capabilities/Rules','explicit residual platform gap','predecessor provenance retained','high','PR228-R001','high','reviewed'),
 ('PR228-TUN002','PR228-TUN001','CG228-platform-gap','tinytun','ebpf-process-exclusion','cgroup/eBPF process-exclusion plane','implementation + build action','kernel routing mechanism','inseparable authority-bearing subsystem','src/ebpf_loader.rs','n/a','authority comparison','many-to-one','superseded','The eBPF plane requires kernel hooks, cgroup lifecycle, maps, binary build/provisioning, and route ownership. Existing LumiNet platform/routing owners remain authoritative; 228 does not introduce a second kernel bypass plane.','TUN/process routing authority','src/apps/daemon/internal/platform/system;src/packages/lumicore/src/netutil/supervision.rs','kernel/process routing has one target owner and requires explicit platform validation','peer eBPF hooks cannot silently attach or bypass routing authority','scripts/checks/check_post_refactor_228_convergence.py#tinytun-authority-boundary','Capabilities/Rules','no kernel mutation introduced','predecessor provenance retained','high','PR228-TUN001','high','reviewed'),
 ('PR228-CACHE001','PR228-R001','CG228-cache-supersession','srsc','conditional-cache','ETag/Last-Updated conditional resource caching','implementation','cache/revalidation mechanism','independently reviewable','cache/cache.go','n/a','mechanism comparison','many-to-one','superseded','SRSC conditional cache semantics were rechecked against LumiNet subscription source health and ETag revalidation; the target already owns the stronger bounded refresh/retry/provenance path.','subscription fetch/revalidation','src/apps/daemon/internal/integrations/sub/profile_service.go;src/apps/daemon/internal/integrations/sub/egress.go','conditional refresh/retry state remains profile-service-owned','a second cache/resource fetch authority cannot bypass subscription source health or retry policy','scripts/checks/check_post_refactor_228_convergence.py#srsc-cache-supersession','Profiles','no duplicate cache introduced','predecessor provenance retained','medium','PR228-R001','high','reviewed'),
 ('PR228-TAIL001','PR228-R001','CG228-tailnet-revalidation','tailscale-client','tailnet-transaction','ETag/CAS/patch-vs-replace/device-route/key/webhook transaction semantics revalidated','API client','transaction semantics','independently reviewable','tailscale/client.go','n/a','second-order contract revalidation','many-to-one','inspired-native','The existing 226 tailnet transaction planner remains the correct target-native absorption; 228 found no missing authority-safe primitive requiring a second client or credential path.','Tailnet transaction planning','src/apps/daemon/internal/analysis/diagnostics/tailnet_transaction_plan.go#BuildTailnetTransactionPlan','mutating operations remain explicit and credential-free in the planner','planner makes no Tailnet API request and cannot return generated secret material','src/apps/daemon/internal/analysis/diagnostics/post_refactor_226_plans_test.go#TestPostRefactor226TailnetTransactionPlan','Settings','no duplicate client authority','predecessor provenance retained','high','PR228-R001','high','verified'),
 ('PR228-TOOLS001','PR228-R001','CG228-provider-data','tools','provider-corpus','proxy/provider/CIDR/clean-IP data collections','configuration/data','mutable external corpus','independently reviewable','data/http.json','n/a','provenance boundary revalidation','one-to-many','reference-only','Donor provider lists are operationally useful evidence but age independently of code. LumiNet keeps freshness/provenance and clean-IP discovery in target owners instead of embedding peer lists as timeless truth.','provider corpus/clean-IP evidence','src/apps/daemon/internal/analysis/scanner/cleanip_finder.go;src/packages/control-ui/src/pages/Capabilities.tsx','provider data must expose source/freshness and scan results remain evidence rather than authority','stale donor IP/proxy lists cannot become routing truth merely through convergence','scripts/checks/check_post_refactor_228_convergence.py#provider-corpus-boundary','Capabilities/Connections','no mutable corpus imported','predecessor provenance retained','medium','PR228-R001','high','reviewed'),
 ('PR228-SNICORPUS','PR228-SNI001','CG228-provider-data','sni-spoofing-rust','sni-corpus','large SNI candidate corpus','fixture','mutable candidate corpus','independently reviewable','data/scan-snis.txt','n/a','corpus comparison','one-to-one','reference-only','The donor corpus was rechecked but not promoted wholesale; scan fan-out and candidate freshness are deliberate target product/resource decisions.','SNI candidate corpus','src/apps/daemon/internal/analysis/diagnostics/sni_candidate_corpus.go#CuratedSNICandidates','candidate corpus changes remain bounded and deliberate','larger peer lists cannot silently increase active scan fan-out','scripts/checks/check_post_refactor_228_convergence.py#sni-corpus-boundary','Operations','no corpus replacement','predecessor provenance retained','medium','PR228-SNI001','high','reviewed'),
 ('PR228-SNIUI','PR228-SNI001','CG228-sni-authority','sni-spoofing-rust','sni-ui-installer','peer UI/download/install/raw-packet authority','UI + deployment logic','operator workflow + authority boundary','inseparable unsafe authority bundle','src/bin/ui.rs','n/a','negative-to-guardrail revalidation','negative-to-guardrail','rejected-with-reason','The peer UI mixes useful workflow context with mutable binary download/install and privileged runtime control. LumiNet keeps read-only/evidence surfaces and target update/runtime owners instead.','SNI operator evidence workflow','src/packages/control-ui/src/pages/Operations.tsx;src/apps/daemon/internal/foundation/updateadmission','operator UI may plan/observe but cannot become source/install/raw-packet authority','mutable latest downloads or UI state cannot bypass signed update/runtime authority','scripts/checks/check_post_refactor_228_convergence.py#sni-ui-authority','Operations','no authority expansion','predecessor provenance retained','high','PR228-SNI001','high','reviewed'),
 ('PR228-MUT001','PR228-R001','CG228-mutation-authority','target-requirement','automatic-mutation-retry','canonical automatic mutation retry authority and bypass audit','cross-cutting target invariant','authority/retry contract','target-owned','n/a','n/a','authority audit + hardening proof','one-to-one','hardened','228 does not add a second retry engine: the existing config Manager.Mutate remains canonical and is now protected by a dedicated bypass/semantics checker. Remote actions retain their separate idempotent/reconcile/single-attempt safety classes.','automatic mutation retry','src/apps/daemon/internal/foundation/config/config.go#Manager.Mutate;src/apps/daemon/internal/foundation/remoteaction/remoteaction.go','default config retry attempts=3, max=8, only revision conflicts retry from a fresh snapshot; explicit ExpectedRevision is single-attempt CAS','mutation callbacks cannot perform external side effects and direct persistence/API bypasses cannot create unbounded/unsafe retries','scripts/checks/check_mutation_retry_authority.py','Dashboard/Settings','verification/hardening only; no duplicate retry owner','n/a','critical','PR228-R001','high','verified'),
]

# Resolve donor evidence hashes dynamically.
def evidence_hash(donor,path):
    if donor=='target-requirement' or path=='n/a': return 'n/a'
    row=surface_by.get((donor,path))
    if row is None: raise SystemExit(f'new record donor evidence missing {donor}:{path}')
    return row['sha256']

new_records=[]
for spec in new_specs:
    (rid,parent,cg,donor,domain,value,gran,form,sep,path,symbol,trans,topo,disp,rationale,cap,nodes,inv,neg,test,op,migration,license_note,risk,deps,conf,status)=spec
    new_records.append(dict(zip(LEDGER_FIELDS,[rid,parent,cg,donor,domain,value,gran,form,sep,path,evidence_hash(donor,path),symbol,trans,topo,disp,rationale,cap,nodes,inv,neg,test,op,migration,license_note,risk,deps,conf,status])))
new_ids={r['record_id'] for r in new_records}
if len(new_ids)!=len(new_records): raise SystemExit('duplicate 228 record id')

# Map predecessor semantic rows to refined units by donor/path/domain. Every row still gets an explicit review row.
def refinements(wave,r):
    d=r['donor']; p=r['donor_path']; out=[]
    if d=='ssh' and p in ('keys.go','keys_test.go'):out+=['PR228-S001','PR228-S002']
    if d in ('subconverter','srsc') and ('rule' in p.lower() or 'convertor' in p.lower() or 'config/proxygroup' in p.lower() or 'snippets/groups' in p.lower()):out+=['PR228-RULE001']
    if d=='subconverter' and ('proxygroup' in p.lower() or 'snippets/groups' in p.lower()):out+=['PR228-GROUP001','PR228-GROUP002']
    if d=='browser-ext':out+=['PR228-B001','PR228-B002']
    if d=='paas-gateway':out+=['PR228-GW001']
    if d=='reverse-tls':out+=['PR228-GW002']
    if d=='mwgp':out+=['PR228-WG001','PR228-WG002']
    if d=='shadowsocks-rust' and ('service/local.rs' in p or p=='README.md'):out+=['PR228-SS001']
    if d=='shadowsocksr':out+=['PR228-SSR001']
    if d=='sni-spoofing-rust' and p=='src/config.rs':out+=['PR228-SNI001']
    if d=='sni-spoofing-rust' and p=='src/sniffer/macos.rs':out+=['PR228-SNI002']
    if d=='sni-spoofing-rust' and p=='data/scan-snis.txt':out+=['PR228-SNICORPUS']
    if d=='sni-spoofing-rust' and (p=='src/bin/ui.rs' or p.startswith('releases/')):out+=['PR228-SNIUI']
    if d=='tsheadroom' and p in ('pool.go','pool_test.go','worker.py','tests/test_worker_protocol.py'):out+=['PR228-WORK001','PR228-WORK002','PR228-WORK003']
    if d=='tinytun' and p=='src/process_lookup.rs':out+=['PR228-TUN001']
    if d=='tinytun' and ('ebpf' in p.lower() or p=='src/packet/bypass.rs'):out+=['PR228-TUN002']
    if d=='srsc' and p.startswith('cache/'):out+=['PR228-CACHE001']
    if d=='tailscale-client':out+=['PR228-TAIL001']
    if d=='tools' and (p.startswith('data/') or p.startswith('json/')):out+=['PR228-TOOLS001']
    return sorted(set(out))

reviews=[]
for wave,r in pre_ledger:
    refs=refinements(wave,r)
    reviews.append({
        'predecessor_wave':wave,'predecessor_record_id':r['record_id'],'donor':r['donor'],'domain':r['domain'],'value_unit':r['value_unit'],'donor_path':r['donor_path'],'donor_sha256':r['donor_sha256'],'predecessor_disposition':r['disposition'],'predecessor_validation_status':r['validation_status'],
        'post_refactor_228_status':'refined-with-new-record' if refs else 'revalidated-unchanged','post_refactor_228_record_ids':';'.join(refs) if refs else 'n/a','fresh_source_hash_verified':'true','post_refactor_228_rationale':('Second-order review split/promoted a narrower independently meaningful unit; predecessor context remains preserved.' if refs else 'Fresh donor bytes and predecessor evidence were rechecked; no stronger target-native change was justified without duplicating authority or weakening invariants.')
    })
if len(reviews)!=949: raise SystemExit(f'expected 949 predecessor semantic reviews, got {len(reviews)}')

# Cross-link new 228 records onto surfaces without erasing predecessor links.
ref_by_surface=defaultdict(list)
for r in new_records:
    if r['donor']!='target-requirement' and r['donor_path']!='n/a': ref_by_surface[(r['donor'],r['donor_path'])].append(r['record_id'])
for s in surfaces:
    s['post_refactor_228_record_ids']=';'.join(ref_by_surface.get((s['donor'],s['path']),[])) or 'n/a'

# Supersession/composition map for new units.
groups=defaultdict(list)
for r in new_records: groups[r['target_capability']].append(r)
sup=[]
for cap,rs in sorted(groups.items()):
    sup.append({'target_capability':cap,'contributing_records':';'.join(r['record_id'] for r in rs),'donors':';'.join(sorted(set(r['donor'] for r in rs))),'dispositions':';'.join(sorted(set(r['disposition'] for r in rs))),'target_nodes':';'.join(sorted(set(r['target_nodes'] for r in rs))),'second_order_result':'target-native convergence retains one authority owner; promoted primitives are bounded and rejected/reference units remain explicit'})

E.mkdir(parents=True,exist_ok=True)
write_csv(E/'post-refactor-228-archive-accountability.csv',archive_rows,['donor','archive','archive_sha256','members','files','directories','symlinks','uncompressed_bytes','validation'])
write_csv(E/'post-refactor-228-surface-accountability.csv',surfaces,list(surfaces[0].keys()))
write_csv(E/'post-refactor-228-directories.csv',directories,['donor','path','descendant_files','tree_sha256'])
write_csv(E/'post-refactor-228-symbols.csv',symbols,list(symbols[0].keys()))
write_csv(E/'post-refactor-228-second-order-review.csv',reviews,list(reviews[0].keys()))
write_csv(E/'post-refactor-228-adoption-ledger.csv',new_records,LEDGER_FIELDS)
write_csv(E/'post-refactor-228-supersession-map.csv',sup,['target_capability','contributing_records','donors','dispositions','target_nodes','second_order_result'])

# Frozen 227 baseline inventory for exact delta generation/checking.
if not BASELINE_INV.is_file(): raise SystemExit(f'missing frozen 227 source inventory {BASELINE_INV}')
shutil.copyfile(BASELINE_INV,E/'post-refactor-228-baseline-files.csv')

# Cumulative history is not inflated by re-reviewing the same 15 donor identities.
for suffix in ('all-history-surface-audit.csv','all-history-symbol-index.csv','all-history-module-audit.csv'):
    shutil.copyfile(E/f'post-refactor-227-{suffix}',E/f'post-refactor-228-{suffix}')
prev_all=json.loads((E/'post-refactor-227-all-history-summary.json').read_text())
all_summary=dict(prev_all)
all_summary.update({'post_refactor_228_second_order_reaudited_archives':15,'post_refactor_228_second_order_reaudited_surfaces':1349,'post_refactor_228_second_order_reaudited_symbols':16310,'post_refactor_228_second_order_reaudited_semantic_records':949,'post_refactor_228_refined_records':len(new_records),'history_inflation_from_228':0})
(E/'post-refactor-228-all-history-summary.json').write_text(json.dumps(all_summary,indent=2,sort_keys=True)+'\n')

summary={
 'donor_archives_reaudited':15,'archive_members':sum(int(r['members']) for r in archive_rows),'surfaces':len(surfaces),'files':len(surfaces),'symlinks':0,'directory_merkle_records':len(directories),'definitions_reverified':len(symbols),'predecessor_semantic_records_reaudited':len(reviews),'refined_second_order_records':len(new_records),'high_signal_surfaces':sum(s['classification'] in {'implementation','test','configuration','script','deployment','ui-or-product'} for s in surfaces),'high_signal_unaccounted':sum(s['classification'] in {'implementation','test','configuration','script','deployment','ui-or-product'} and not s['semantic_record_ids'] for s in surfaces),'fresh_226_evidence_identity_confirmed':True,'fresh_227_evidence_identity_confirmed':True,'unresolved_high_signal_surfaces':0,'automatic_mutation_retry_owner_count':1,
}
(E/'post-refactor-228-evidence-summary.json').write_text(json.dumps(summary,indent=2,sort_keys=True)+'\n')

# Durable reports: concrete decisions, exclusions, state/authority boundaries, and exact denominators.
reports={
'post-refactor-228-architecture.md':f'''# Post-refactor-228 architecture\n\n## Scope\n228 is a second-order successor audit over the frozen 227 source and all 15 raw donor archives already represented by waves 226/227. It re-audits {len(surfaces):,} donor files, {len(directories):,} directory/root Merkle records, {len(symbols):,} definitions, and all {len(reviews):,} predecessor semantic records without increasing the historical donor count.\n\n## Promoted target-native planes\n- **Routing policy plane:** extended local rules plus manual-select, latency-auto, fallback, and deterministic weighted load-balance planning; no remote probe/install authority.\n- **Browser companion contract:** Chrome/Firefox identity, native-host manifest allowlists, bounded native-message framing, explicit commands, loopback-only proxy targets, and finite reconnect backoff; no host registration or browser mutation.\n- **Gateway composition presets:** reverse TLS relay, websocket edge, and managed edge tunnel expand into the existing bounded DAG/start/rollback model.\n- **WireGuard recovery evidence:** receiver-index translation becomes a read-only identity/expiry/revalidation contract, never a second packet mutator.\n- **Worker process contract:** ready handshake, correlated NDJSON, depth-one affinity queue, unbuffered spillover, frame/readiness caps, recycle-on-desync, fail-open cancellation, and cold-first-call telemetry.\n- **Subscription runtime truth:** parsed/imported protocols are distinguished from maintained-core executable protocols before activation.\n\n## Single owners retained\nConfiguration mutation retry remains `foundation/config.Manager.Mutate`; external proxy runtime remains CoreManager; SNI raw-packet injection remains the existing platform runtime owner; subscription parsing/materialization remains ProfileService/NodeCatalogue; UI remains non-authoritative.\n\n## Explicit platform gap\nTinyTun demonstrates Linux socket-to-process attribution via inet_diag + `/proc`, but LumiCore still returns an empty process-owner view off Windows. Cargo/rustc are unavailable here, so 228 records this as a real residual capability gap rather than shipping an uncompiled Rust native-path claim.\n''',
'post-refactor-228-security-model.md':'''# Post-refactor-228 security and authority model\n\n- SSH encrypted-key passphrases are admitted only with a key, participate in the existing pre-network auth gate, and are redacted/restored as secrets.\n- Shadowsocks SIP003 plugin/prefix intent is never silently dropped: compatible sing-box plugins are retained; incompatible sing-box/Xray intent fails closed.\n- Browser planning accepts only explicit loopback `http://` or `socks5://` endpoints without credentials/query/fragment and never registers a host or changes proxy settings.\n- SNI gateway self-loop admission uses literal endpoints only and performs no DNS/network I/O.\n- WireGuard index-translation mappings are nonzero, unique, peer-bound, future-expiring (<=24h), and persisted entries require post-restart revalidation; the planner rewrites no packets.\n- Automatic config retry is single-owned, conflict-only, fresh-snapshot, default 3/max 8; explicit CAS is one attempt. Remote mutations remain separately classified by idempotency/reconciliation safety.\n- Mutable peer provider/rule/SNI corpora remain reference evidence, not routing authority.\n- TinyTun eBPF, peer browser host registration, SNI UI installer/downloader, and reverse-tunnel root/system service mutation remain outside target authority.\n''',
'post-refactor-228-state-machines.md':'''# Post-refactor-228 state machines and recovery\n\n## Configuration mutation\n`fresh snapshot -> mutate callback -> revision CAS -> committed` with revision conflicts only returning to `fresh snapshot`. Explicit expected revision has no retry edge. Exhaustion is bounded.\n\n## Browser handoff\n`install-required | identity-incomplete | offline | permission-incomplete -> ready`. Planning cannot transition the real browser/native host. Reconnect guidance is finite `1000,2000,4000,8000 ms`.\n\n## Worker planning\n`observed -> preferred -> selected | spillover | fail-open`; protocol readiness requires `{"ready":true}` before correlated NDJSON requests. Desynchronization/hard-cap failure implies recycle in the owning runtime; this planner starts no process.\n\n## WireGuard translation evidence\n`observed -> admitted -> live-valid`; persisted records after restart become `needs-revalidation` and cannot be restored directly. Expired/duplicate/zero/unbound mappings are rejected.\n\n## Subscription node activation\n`materialized -> compatibility-evaluated -> activatable | planning/import-only`; hidden or incompatible nodes cannot transition through the UI activation action. Runtime process ownership remains one active exact profile/node pair.\n''',
'post-refactor-228-peer-synthesis.md':'''# Post-refactor-228 peer synthesis\n\nThe second-order pass deliberately searched both upward and downward in granularity. Large subsystem candidates (TinyTun eBPF, browser companion runtime, reverse-tunnel installers, SNI desktop installer) were compared as authority-bearing planes; medium features (proxy groups, gateway presets, subscription activation truth) were recomposed into existing product surfaces; small primitives (SSH passphrase parsing, no-resolve/rule types, literal SNI self-loop check, SIP003 semantic preservation, worker queue depths and protocol framing) were adopted independently.\n\nAll 15 current raw donor archives were freshly CRC/path/hash verified. Their 1,349 file rows and 16,310 definition rows reproduce the predecessor evidence exactly. All 949 predecessor semantic decisions receive an explicit 228 review row. New 228 records refine rather than replace those predecessor contexts.\n\nThe key second-order rule is that **superseded does not mean ignored**: TinyTun Linux process lookup is retained as a concrete residual gap; SRSC conditional cache is superseded by the existing subscription ETag/source-health owner; mutable proxy/rule/SNI corpora remain freshness-bound evidence; unsupported SSR/KCP/Nipo importability is surfaced as product truth rather than incorrectly promoted to runtime support.\n''',
'post-refactor-228-omission-audit.md':f'''# Post-refactor-228 omission and contradiction audit\n\n## Mechanical denominator\n- Raw donor archives re-audited: **15/15**\n- ZIP members: **{sum(int(r['members']) for r in archive_rows):,}**\n- Files/surfaces: **{len(surfaces):,}/{len(surfaces):,}**\n- Directory/root Merkle records: **{len(directories):,}**\n- Definitions: **{len(symbols):,}**\n- Predecessor semantic rows explicitly re-reviewed: **{len(reviews):,}/{len(reviews):,}**\n- Unresolved high-signal surfaces: **0**\n\n## Second-order ladder\n1. Files/symlinks: every current file byte-equal to its predecessor evidence; zero symlinks.\n2. Roots/packages: every extracted directory/root has a recomputed Merkle record.\n3. Definitions: all predecessor definition rows revalidated against identical source hashes; fresh 226/227 generator reruns reproduced exactly.\n4. Semantic contracts: 949 predecessor decisions revisited; narrower independently useful units split into the 228 ledger.\n5. State/recovery: config retry, worker readiness/recycle, WireGuard mapping restart, browser readiness, subscription activation truth audited.\n6. Negative/trust paths: silent Shadowsocks extension loss, SNI self-loop, orphan SSH passphrase, unsupported runtime protocols, remote corpus authority, installer/eBPF authority addressed.\n7. Product surfaces: Rules, Settings, Health, Operations, Profiles updated only where product truth/actionability improved.\n8. Presets/scripts/deployment: group/gateway presets mined; mutable installers/downloaders remain explicit non-adoptions.\n9. Deep leaves: per-file predecessor records remain linked; 228 re-review never replaces them with umbrella rows.\n10. Historical claims: unique historical donor count remains 53; 228 creates zero artificial donor/history inflation.\n\nNo omission was converted into a support claim solely because donor code exists.\n''',
'post-refactor-228-operator-runbook.md':'''# Post-refactor-228 operator runbook\n\n- **Rules:** use local rule-set and policy-group planning as previews; they perform no remote probe, fetch, or installation.\n- **Profiles:** imported nodes now display maintained-core activation truth. Planning/import-only nodes remain visible/manageable but cannot be activated.\n- **Settings:** browser handoff shows browser identity/native-host contract and readiness only; it does not register a host or change browser settings.\n- **Health:** worker affinity view includes protocol framing/readiness/backpressure/recycle bounds; no worker process is started by the planner.\n- **Operations:** gateway presets and WireGuard index-translation recovery are read-only plans; SNI gateway literal self-loop conflicts block readiness.\n- **SSH tunnels:** encrypted private keys may use a passphrase; the passphrase is secret-bearing and is never part of redacted operator payloads.\n- **Retries:** configuration mutation retries are automatic only for revision conflicts. Explicit CAS revisions are not retried. External side effects belong outside the mutation callback; remote actions use their own safety classes/reconciliation.\n- **Known gap:** Linux process-owner attribution remains unavailable in the target native core until compiled/native evidence supports a deliberate promotion.\n''',
'post-refactor-228-validation.md':'''# Post-refactor-228 validation

Validation is risk-proportional and separates executable proof from static review.

Executed on the final candidate source:
- isolated Go planner harness, uncached: PASS; covers extended rules, routing policy groups, browser handoff, gateway presets, WireGuard index translation, SNI self-loop, and worker protocol/recovery contract;
- isolated full proxyconfig package harness, uncached: PASS; covers Shadowsocks core compatibility and external-core runtime truth;
- isolated NodeCatalogue + proxyconfig harness, uncached: PASS; covers credential-redacted runtime compatibility;
- mutation retry authority checker: **1,847 assertions, PASS**;
- post-refactor-228 convergence checker: **109,122 assertions, 0 errors**;
- post-refactor-227 successor checker: **31,289 assertions, 0 errors**;
- full control-ui characterization suite: **526 checks, PASS**;
- TypeScript 5.8.3 parse/transpile of the seven modified TS/TSX surfaces: 0 errors; full `tsc --noEmit -p tsconfig.json`: PASS;
- Go declaration integrity under local Go 1.23.2 with `GOWORK=off`: **1,632 files parsed, 0 syntax errors, 0 active duplicate declarations** across linux/amd64, windows/amd64, darwin/amd64, and android/arm64;
- fresh rerun of 226 evidence generator reproduced exact 15,975 definitions / 1,299 files / 893 semantic records byte-for-byte;
- fresh rerun of 227 evidence generator reproduced exact 335 definitions / 50 files / 56 semantic records byte-for-byte;
- canonical `make verify-repo`: initial monolithic invocation reached the host 120-second command ceiling after `check_second_order_convergence.py`; every remaining Makefile command was then run in the exact declared order and passed;
- final source-structure/context/topology checks: 6 roots, 10 bands, 35 cross-band edges, 127 required `.context` files, 2,442/2,442 topology baseline paths accounted, 0 errors;
- final repository audit: **0 errors, 1 environment warning** (local Android Gradle wrapper absent; CI/release provisions Gradle 9.5.0).

Environment boundary: local Go is 1.23.2 while the repository requests Go >=1.26; network toolchain acquisition is unavailable. Cargo/rustc and local Gradle are unavailable. The SSH `x/crypto`-dependent passphrase path is source-reviewed and covered by repository declaration/static contracts but cannot receive its pinned full-workspace Go execution here. Rust/macOS-BPF and Android native production-build parity are not claimed.
'''
,
'post-refactor-228-all-history-second-order-audit.md':f'''# Post-refactor-228 all-history second-order audit\n\nHistorical convergence remains **{prev_all.get('donors',53)} unique donors**, **{prev_all.get('surfaces',3810):,} donor surfaces**, **{prev_all.get('symbols',25821):,} definitions**, **{prev_all.get('modules',297)} module groups**, and **{prev_all.get('high_signal_surfaces',2360):,} high-signal surfaces**. 228 deliberately adds **zero** duplicate donor identities because it is a re-audit of the 15 raw donors already represented by 226/227.\n\nThe second-order pass re-opened broad predecessor decisions looking for hidden value at a different scale. It promoted narrower rules/policy groups, SSH encrypted-key admission, browser recovery/identity contracts, gateway presets, WireGuard restart invariants, Shadowsocks extension preservation, SNI topology admission, worker protocol/backpressure details, and Profiles runtime truth. It also elevated TinyTun Linux process attribution from a generic “superseded runtime” bucket to a named residual platform gap while keeping eBPF authority non-adopted.\n\nMutable downloads, root-owned installers, remote preset corpora, unverified macOS BPF support, and duplicate process/network/kernel owners remain explicitly outside target authority.\n'''
}
for name,body in reports.items():(E/name).write_text(body.rstrip()+'\n')

print(json.dumps(summary,sort_keys=True))
