#!/usr/bin/env python3
"""Generate deterministic post-refactor-232 evidence for four donor archives."""
from __future__ import annotations
import csv, hashlib, json, os, shutil
from collections import defaultdict
from pathlib import Path

ROOT=Path(os.environ.get('LUMINET_232_TARGET_ROOT',Path(__file__).resolve().parents[2]))
WORK=Path(os.environ.get('LUMINET_232_WORK_ROOT','/mnt/data/luminet232_work'))
RAW=WORK/'evidence'; OUT=ROOT/'governance'/'convergence'
BASELINE=Path(os.environ.get('LUMINET_232_BASELINE_INVENTORY','/mnt/data/LumiNet-post-refactor-231-source-inventory.csv'))
DONORS=['splitpt','dns-tunnel-deploy','outline-client','pydns-scanner']
ROOTS={'splitpt':'splitpt-main','dns-tunnel-deploy':'dns-tunnel-deploy-main','outline-client':'outline-client-master','pydns-scanner':'PYDNS-Scanner-main'}
HIGH={'implementation','ui-or-product','configuration','deployment','script','test'}
LEDGER_FIELDS=['record_id','parent_record_id','composition_group_id','donor','domain','value_unit','source_granularity','value_form','separability','donor_path','donor_sha256','donor_symbol','transformation','mapping_topology','disposition','decision_rationale','target_capability','target_nodes','invariant','negative_invariant','test_node','operator_surface','migration_impact','license_note','risk_tier','dependency_record_ids','evidence_confidence','validation_status']

def read_csv(p):
    with Path(p).open(newline='',encoding='utf-8') as f:return list(csv.DictReader(f))
def write_csv(p,rows,fields):
    p=Path(p);p.parent.mkdir(parents=True,exist_ok=True)
    with p.open('w',newline='',encoding='utf-8') as f:
        w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore',lineterminator='\n');w.writeheader()
        for r in rows:w.writerow({k:r.get(k,'n/a') for k in fields})
def sha_file(p):
    h=hashlib.sha256()
    with Path(p).open('rb') as f:
        for b in iter(lambda:f.read(1<<20),b''):h.update(b)
    return h.hexdigest()
def sha_text(s):return hashlib.sha256(s.encode()).hexdigest()
def donor_root(d):return WORK/'donors'/d/ROOTS[d]
def donor_file_sha(d,p):return sha_file(donor_root(d)/p)

def focus_specs():
    F=[]
    def add(d,domain,value,path,trans,disp,rationale,cap,nodes,test='scripts/checks/check_post_refactor_232_convergence.py',inv='selected semantics remain explicit, bounded, deterministic, and target-owned',neg='donor runtime or authority is not imported implicitly',surface='governance',risk='medium',status='reviewed',form='behavioral evidence'):
        F.append(dict(donor=d,domain=domain,value=value,path=path,transformation=trans,disposition=disp,rationale=rationale,capability=cap,nodes=nodes,test=test,invariant=inv,negative=neg,surface=surface,risk=risk,status=status,form=form))
    # SplitPT: preserve scheduling/framing semantics without importing a second PT runtime.
    add('splitpt','multipath','round-robin path scheduling','common/split/round-robin.go','primitive extraction','adapted','Per-packet round-robin scheduling becomes a deterministic read-only schedule preview.','multipath transport scheduling','src/apps/daemon/internal/analysis/diagnostics/multipath_transport_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',surface='Operations',status='verified')
    add('splitpt','multipath','random path scheduling','common/split/random.go','deterministic adaptation','adapted','Random donor selection is converted to keyed deterministic scheduling so planning is reproducible.','multipath transport scheduling','src/apps/daemon/internal/analysis/diagnostics/multipath_transport_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',neg='hidden unseeded randomness cannot become policy authority',surface='Operations',status='verified')
    add('splitpt','multipath','strict algorithm admission','client/lib/client-config.go','guard extraction','adapted','Only explicit round-robin/random scheduling is admitted.','multipath transport admission','src/apps/daemon/internal/analysis/diagnostics/multipath_transport_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',surface='Operations',status='verified')
    add('splitpt','framing','8-byte cryptographically random session identifier','common/turbotunnel/sessionid.go','constraint extraction','adapted','The donor session identity width is retained as an explicit framing invariant; the planner does not generate runtime session keys.','multipath framing truth','src/apps/daemon/internal/analysis/diagnostics/multipath_transport_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',surface='Operations',status='verified')
    add('splitpt','framing','two-byte length prefix and 65535-byte packet ceiling','common/turbotunnel/encapsulation.go','guard extraction','hardened','The uint16 framing limit is surfaced as pre-runtime admission rather than donor panic behavior.','multipath framing truth','src/apps/daemon/internal/analysis/diagnostics/multipath_transport_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',neg='oversized packets are rejected before framing rather than panicking',surface='Operations',status='verified')
    add('splitpt','backpressure','32-packet send/receive queue default','common/turbotunnel/queuepacketconn.go','bounds adaptation','adapted','Queue capacity becomes an explicit bounded request with donor-compatible default and a target maximum.','multipath backpressure policy','src/apps/daemon/internal/analysis/diagnostics/multipath_transport_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',surface='Operations',status='verified')
    add('splitpt','backpressure','silent drop when send queue is full','common/turbotunnel/queuepacketconn.go','negative-to-guardrail','superseded','Silent packet loss is replaced by explicit backpressure or reject-new policy.','multipath backpressure policy','src/apps/daemon/internal/analysis/diagnostics/multipath_transport_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',neg='queue overflow never silently discards traffic by default',surface='Operations',risk='high',status='verified')
    add('splitpt','recovery','fatal transport errors and incomplete redial/deadline recovery','common/turbotunnel/redialpacketconn.go','negative-to-guardrail','reference-only','Donor recovery limitations are retained as a reason not to promote its runtime. Existing LumiNet retry/lifecycle owners remain authoritative.','transport recovery ownership','governance/convergence/post-refactor-232-peer-synthesis.md',neg='planner success cannot imply live redial/deadline recovery',surface='governance',risk='high')
    add('splitpt','pluggable-transport','Lyrebird-only transport binding','client/lib/lyrebird.go','mechanism comparison','superseded','LumiNet already owns broader PT lifecycle/admission; SplitPT does not become a parallel PT process owner.','pluggable transport ownership','src/apps/daemon/internal/analysis/diagnostics/pluggable_transport_plan.go',neg='multipath planning cannot start Lyrebird or other PT processes',surface='Operations')
    add('splitpt','test-fixtures','Shadow/Tor private-key fixtures','tests/shadow/shadow.data.template/hosts/4uthority/keys/authority_identity_key','negative-to-guardrail','rejected','Secret-bearing simulation fixtures are evidence only and never become product credentials or defaults.','fixture secret boundary','governance/convergence/post-refactor-232-security-model.md',neg='donor test keys are never imported into runtime configuration',surface='governance',risk='high')
    add('splitpt','simulation','Shadow/Tor network test topology','tests/shadow/shadow.yaml','test-oracle retention','reference-only','The topology is retained as simulation knowledge but not copied into production routing.','circumvention simulation evidence','governance/convergence/post-refactor-232-peer-synthesis.md',surface='governance')
    # DNS tunnel deploy.
    add('dns-tunnel-deploy','dns-delegation','A/AAAA nameserver glue plus delegated NS record','dnstt-deploy.sh','configuration extraction','adapted','Required DNS delegation is modeled explicitly before host mutation.','DNSTT deployment preflight','src/apps/daemon/internal/networking/dnstunnel/deployment_plan.go','src/apps/daemon/internal/networking/dnstunnel/deployment_plan_test.go',surface='Operations',status='verified')
    add('dns-tunnel-deploy','dns-tunnel','1232 MTU default and 512..1400 operational range','dnstt-deploy.sh','bounds extraction','adapted','MTU becomes a validated planning parameter without OS mutation.','DNSTT deployment preflight','src/apps/daemon/internal/networking/dnstunnel/deployment_plan.go','src/apps/daemon/internal/networking/dnstunnel/deployment_plan_test.go',surface='Operations',status='verified')
    add('dns-tunnel-deploy','listener-boundary','unprivileged UDP/5300 listener plus UDP/53 redirect','dnstt-deploy.sh','boundary extraction','adapted','Privileged port ownership is separated from the DNSTT service listener.','DNSTT deployment preflight','src/apps/daemon/internal/networking/dnstunnel/deployment_plan.go','src/apps/daemon/internal/networking/dnstunnel/deployment_plan_test.go',surface='Operations',risk='high',status='verified')
    add('dns-tunnel-deploy','service-identity','non-login dnstt service account','dnstt-deploy.sh','least-privilege extraction','adapted','Service identity is modeled as a bounded Unix account name and disclosed before deployment.','DNSTT deployment preflight','src/apps/daemon/internal/networking/dnstunnel/deployment_plan.go','src/apps/daemon/internal/networking/dnstunnel/deployment_plan_test.go',surface='Operations',status='verified')
    add('dns-tunnel-deploy','key-lifecycle','per-domain key generation/reuse','dnstt-deploy.sh','negative-to-guardrail','adapted','Planner models key lifecycle but generates no keys and returns no private material.','DNSTT key boundary','src/apps/daemon/internal/networking/dnstunnel/deployment_plan.go','src/apps/daemon/internal/networking/dnstunnel/deployment_plan_test.go',neg='private keys remain release/deployment-owner state and are not exposed by the planner',surface='Operations',risk='high',status='verified')
    add('dns-tunnel-deploy','service-management','systemd service unit hardening and enable/start sequence','dnstt-deploy.sh','workflow extraction','adapted','Mutation steps are represented as an ordered dry-run with rollback rather than executed by the API.','DNSTT deployment preflight','src/apps/daemon/internal/networking/dnstunnel/deployment_plan.go','src/apps/daemon/internal/networking/dnstunnel/deployment_plan_test.go',surface='Operations',status='verified')
    add('dns-tunnel-deploy','forward-target','SOCKS/SSH local forward target modes','dnstt-deploy.sh','configuration extraction','adapted','Target mode/port are validated before deployment planning.','DNSTT deployment preflight','src/apps/daemon/internal/networking/dnstunnel/deployment_plan.go','src/apps/daemon/internal/networking/dnstunnel/deployment_plan_test.go',surface='Operations',status='verified')
    add('dns-tunnel-deploy','deployment-authority','root download/install/update/firewall/service mutation','dnstt-deploy.sh','negative-to-guardrail','rejected','Root deployment authority is not exposed through LumiNet planning endpoints.','deployment authority boundary','src/apps/daemon/internal/networking/dnstunnel/deployment_plan.go','src/apps/daemon/internal/networking/dnstunnel/deployment_plan_test.go',neg='planner performs no download, firewall/systemd mutation, key generation, or service restart',surface='Operations',risk='high',status='verified')
    add('dns-tunnel-deploy','rollback','firewall persistence and cleanup sequence','dnstt-deploy.sh','recovery extraction','adapted','Task-owned redirect/service changes receive explicit rollback ordering while keys are retained unless destruction is explicit.','DNSTT rollback planning','src/apps/daemon/internal/networking/dnstunnel/deployment_plan.go','src/apps/daemon/internal/networking/dnstunnel/deployment_plan_test.go',surface='Operations',status='verified')
    add('dns-tunnel-deploy','operator-ui','desktop DNSTT manager wrapper','gui/dnstt_manager.py','product comparison','reference-only','GUI workflow informs operator language but does not gain host mutation authority.','DNSTT operator planning','src/packages/control-ui/src/pages/Operations.tsx','src/packages/control-ui/scripts/test-post-refactor-232.mjs',surface='Operations',status='verified')
    # Outline.
    add('outline-client','access-key','static ss:// access-key parsing','src/www/app/outline_server_repository/access_key_serialization.ts','primitive extraction','adapted','Static Outline keys reuse canonical Shadowsocks parsing and runtime compatibility truth.','Outline access-key admission','src/apps/daemon/internal/analysis/diagnostics/outline_access_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',surface='Operations',status='verified')
    add('outline-client','invite-import','static ss:// key embedded in HTTP(S) invite fragment','src/www/app/app.ts','vertical adaptation','adapted','Static invite fragments are unwrapped locally before generic subscription parsing, with no URL fetch.','Outline static invite ingestion','src/apps/daemon/internal/integrations/sub/outline_import.go;src/apps/daemon/internal/integrations/sub/ingest.go','src/apps/daemon/internal/integrations/sub/outline_import_test.go',neg='invite URL content is never fetched merely to unwrap a static fragment',surface='Profiles',status='verified')
    add('outline-client','dynamic-config','ssconf:// to HTTPS remote configuration resolution','src/www/app/outline_server_repository/access_key_serialization.ts','authority separation','adapted','Dynamic access keys become an HTTPS fetch proposal only; live retrieval must later pass canonical guarded egress.','Outline dynamic access planning','src/apps/daemon/internal/analysis/diagnostics/outline_access_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',neg='planner performs no ssconf fetch or redirect following',surface='Operations',risk='high',status='verified')
    add('outline-client','shadowsocks-prefix','static access-key prefix compatibility','src/www/app/outline_server_repository/access_key_serialization.ts','mechanism comparison','superseded','Existing canonical proxyconfig and external-core compatibility own SIP003/prefix support and fail closed where unsupported.','Shadowsocks compatibility truth','src/apps/daemon/internal/networking/proxyconfig/core_compat.go','scripts/checks/check_post_refactor_228_convergence.py',surface='Profiles',status='verified')
    add('outline-client','connection-lifecycle','CONNECTED/DISCONNECTED/RECONNECTING state model','src/www/app/tunnel.ts','state-model comparison','reference-only','State naming reinforces existing LumiNet reconnect/runtime truth; no duplicate tunnel state owner is introduced.','connection lifecycle truth','src/apps/daemon/internal/runtime/proxy/auto_reconnect.go','scripts/checks/check_post_refactor_232_convergence.py',surface='governance')
    add('outline-client','repository','persisted server repository with per-entry load isolation','src/www/app/outline_server_repository/index.ts','recovery comparison','reference-only','Per-entry corruption isolation is retained as profile-store design evidence; existing profile persistence remains authoritative.','profile persistence recovery','governance/convergence/post-refactor-232-peer-synthesis.md',surface='governance')
    add('outline-client','operator-undo','forget server with undo event','src/www/model/events.ts','product inspiration','reference-only','Undo semantics are retained as product evidence without creating a parallel profile mutation workflow.','profile mutation UX','src/packages/control-ui/src/pages/Profiles.tsx','scripts/checks/check_post_refactor_232_convergence.py',surface='Profiles')
    add('outline-client','error-taxonomy','platform tunnel error taxonomy','src/www/model/errors.ts','error-model comparison','reference-only','Error categories are retained as operator/error-mapping evidence while runtime errors stay target-owned.','runtime error taxonomy','governance/convergence/post-refactor-232-peer-synthesis.md',surface='governance')
    add('outline-client','packet-path','TUN to tun2socks to Shadowsocks packet lifecycle','docs/life_of_a_packet.md','architecture comparison','reference-only','Packet-path documentation is retained as architecture evidence; LumiNet does not import Outline tunnel ownership.','tunnel architecture evidence','governance/convergence/post-refactor-232-architecture.md',surface='governance')
    add('outline-client','url-interception','clipboard/deep-link access-key interception','src/www/app/app.ts','negative-to-guardrail','superseded','Only explicit local parsing paths are adopted; ambient clipboard/navigation authority is not required.','import authority boundary','src/apps/daemon/internal/integrations/sub/outline_import.go','src/apps/daemon/internal/integrations/sub/outline_import_test.go',neg='static invite ingestion requires supplied content and performs no ambient clipboard/navigation action',surface='Profiles',status='verified')
    add('outline-client','native-tunnel','platform tunnel service runtime','outline/device/device.go','mechanism comparison','superseded','Existing LumiNet runtime/core owners remain authoritative; Outline native tunnel code is not imported.','runtime ownership','governance/convergence/post-refactor-232-architecture.md',surface='governance',risk='high')
    # PYDNS.
    add('pydns-scanner','campaign-lifecycle','background scanner start/pause/resume/stop state','python/scanner/worker_pool.py','state-model adaptation','adapted','Closed lifecycle transitions become read-only campaign planning evidence.','DNS resolver campaign planning','src/apps/daemon/internal/analysis/diagnostics/dns_resolver_campaign_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',surface='Operations',status='verified')
    add('pydns-scanner','concurrency','semaphore-bounded scanner concurrency','python/scanner/worker_pool.py','bounds adaptation','adapted','Concurrency defaults to 100 and is bounded before a campaign can start.','DNS resolver campaign planning','src/apps/daemon/internal/analysis/diagnostics/dns_resolver_campaign_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',surface='Operations',status='verified')
    add('pydns-scanner','batching','queue worker chunk size max(4,min(16,concurrency/4))','python/scanner/worker_pool.py','primitive extraction','adapted','The donor batching formula is preserved exactly as deterministic planning evidence.','DNS resolver campaign planning','src/apps/daemon/internal/analysis/diagnostics/dns_resolver_campaign_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',surface='Operations',status='verified')
    add('pydns-scanner','result-drain','bounded result retrieval default 500','python/scanner/worker_pool.py','bounds extraction','adapted','Result-drain size is explicit and bounded to prevent unbounded UI/backend drains.','DNS resolver campaign planning','src/apps/daemon/internal/analysis/diagnostics/dns_resolver_campaign_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',surface='Operations',status='verified')
    add('pydns-scanner','dns-cache','random subdomain cache busting','python/scanner/utils.py','deterministic adaptation','adapted','Unseeded random cache-bust labels are replaced by deterministic SHA-256-derived planning labels.','DNS resolver campaign planning','src/apps/daemon/internal/analysis/diagnostics/dns_resolver_campaign_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',neg='hidden randomness does not make planner output non-reproducible',surface='Operations',status='verified')
    add('pydns-scanner','dns-query','A/AAAA/MX/TXT/NS query types','python/scanner/constants.py','vocabulary extraction','adapted','Common DNS query types are admitted and target adds CNAME as an explicit compatible extension.','DNS resolver campaign planning','src/apps/daemon/internal/analysis/diagnostics/dns_resolver_campaign_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',surface='Operations',status='verified')
    add('pydns-scanner','candidate-order','randomized subnet/IP scan order','python/scanner/ip_streaming.py','negative-to-guardrail','superseded','Target planning remains deterministic; live scanner sampling/order remains an execution-owner concern.','deterministic campaign planning','src/apps/daemon/internal/analysis/diagnostics/dns_resolver_campaign_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',neg='planner output never depends on hidden random shuffle state',surface='Operations',status='verified')
    add('pydns-scanner','large-input','CIDR streaming and memory-mapped input','python/scanner/ip_streaming.py','mechanism comparison','reference-only','Streaming/mmap techniques are retained as scanner scalability evidence; this planner enumerates counts, not candidates.','scanner scalability evidence','governance/convergence/post-refactor-232-peer-synthesis.md',surface='governance')
    add('pydns-scanner','results','result ranking/saving pipeline','python/scanner/results.py','product comparison','reference-only','Ranking/export semantics are retained as operator evidence while LumiNet scanner/result owners remain authoritative.','scanner result UX','governance/convergence/post-refactor-232-peer-synthesis.md',surface='governance')
    add('pydns-scanner','slipstream','Slipstream proxy-test mode','python/scanner/slipstream.py','mode extraction','adapted','Slipstream is represented as a campaign mode without starting/downloading its client.','DNS resolver campaign planning','src/apps/daemon/internal/analysis/diagnostics/dns_resolver_campaign_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',surface='Operations',status='verified')
    add('pydns-scanner','slipnet','SlipNet/DNSTT mode and query-size semantics','python/scanner/slipnet.py','bounds extraction','adapted','SlipNet mode admits query_size 0 or 50..4096; other modes reject the field.','DNS resolver campaign planning','src/apps/daemon/internal/analysis/diagnostics/dns_resolver_campaign_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',surface='Operations',status='verified')
    add('pydns-scanner','binary-authority','bundled Slipstream/SlipNet executables and auto-download/chmod','python/scanner/slipstream.py','negative-to-guardrail','rejected','Planner never downloads, installs, chmods, or executes bundled/remote clients.','external-client authority boundary','src/apps/daemon/internal/analysis/diagnostics/dns_resolver_campaign_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',neg='binary acquisition/execution remains outside planner authority',surface='Operations',risk='high',status='verified')
    add('pydns-scanner','host-mutation','OS MTU adjustment around proxy tests','python/scanner/proxy_testing.py','negative-to-guardrail','rejected','Host MTU changes are excluded from scanner planning authority.','host-network mutation boundary','src/apps/daemon/internal/analysis/diagnostics/dns_resolver_campaign_plan.go','src/apps/daemon/internal/analysis/diagnostics/post_refactor_232_plans_test.go',neg='planner cannot mutate interface MTU',surface='Operations',risk='high',status='verified')
    add('pydns-scanner','platform-loop','Windows Proactor versus other asyncio event-loop behavior','python/scanner/worker_pool.py','platform comparison','reference-only','Platform-specific event-loop ownership remains runtime evidence, not planner authority.','scanner runtime evidence','governance/convergence/post-refactor-232-peer-synthesis.md',surface='governance')
    add('pydns-scanner','operator-ui','TUI widgets, pause/resume controls and progress surfaces','python/scanner/widgets.py','product inspiration','reference-only','Operator affordances inform campaign status presentation while the current policy lab remains read-only.','campaign operator UX','src/packages/control-ui/src/pages/Operations.tsx','src/packages/control-ui/scripts/test-post-refactor-232.mjs',surface='Operations',status='verified')
    return F

def main():
    OUT.mkdir(parents=True,exist_ok=True)
    archives=read_csv(RAW/'archive_summary_raw.csv'); surfaces=read_csv(RAW/'surface_accountability_raw.csv'); dirs=read_csv(RAW/'directory_merkle_raw.csv'); defs=read_csv(RAW/'definition_index_raw.csv'); syms=read_csv(RAW/'symlinks_normalized_raw.csv')
    assert len(archives)==len(DONORS)==4
    assert {r['donor'] for r in surfaces}==set(DONORS)
    focus=focus_specs()
    # Validate focus donor paths now; target references may be generated later in this same cycle.
    for f in focus:
        p=donor_root(f['donor'])/f['path']
        if not p.is_file(): raise RuntimeError(f"focused donor path missing: {f['donor']}:{f['path']}")
    # Baseline inventory is embedded byte-for-byte for successor proof.
    shutil.copyfile(BASELINE,OUT/'post-refactor-232-baseline-files.csv')
    shutil.copyfile(RAW/'archive_summary_raw.csv',OUT/'post-refactor-232-archive-accountability.csv')
    write_csv(OUT/'post-refactor-232-directories.csv',dirs,list(dirs[0].keys()) if dirs else ['donor','directory','tree_sha256'])
    write_csv(OUT/'post-refactor-232-symbols.csv',defs,list(defs[0].keys()) if defs else ['donor','path','sha256','line','kind','symbol','snippet'])
    write_csv(OUT/'post-refactor-232-symlinks.csv',syms,list(syms[0].keys()) if syms else ['donor','path','target','mode','module'])

    bymodule=defaultdict(list)
    for r in surfaces:bymodule[(r['donor'],r['module'])].append(r)
    repo_id={d:f"PR232-R{i+1:03d}" for i,d in enumerate(DONORS)}
    modkeys=sorted(bymodule); mod_id={k:f"PR232-M{i+1:04d}" for i,k in enumerate(modkeys)}
    filekeys=sorted((r['donor'],r['path']) for r in surfaces); file_id={k:f"PR232-F{i+1:05d}" for i,k in enumerate(filekeys)}
    focus_id={i:f"PR232-S{i+1:03d}" for i in range(len(focus))}
    focus_by_path=defaultdict(list)
    for i,f in enumerate(focus):focus_by_path[(f['donor'],f['path'])].append(focus_id[i])

    module_rows=[]
    for d,m in modkeys:
        rows=bymodule[(d,m)]; layers=sorted({r['classification'] for r in rows})
        h=hashlib.sha256()
        for r in sorted(rows,key=lambda x:x['path']):h.update(f"{r['path']}\0{r['sha256']}\0{r['classification']}\n".encode())
        ids=[]
        for r in rows:ids += focus_by_path.get((d,r['path']),[])
        outcome='focused-adoption-or-guardrail' if ids else ('reviewed-target-fit' if any(r['classification'] in HIGH for r in rows) else 'accounted-reference')
        module_rows.append(dict(wave='232',donor=d,module=m,surfaces=len(rows),high_signal_surfaces=sum(r['classification'] in HIGH for r in rows),ui_product_surfaces=sum(r['classification']=='ui-or-product' for r in rows),implementation_surfaces=sum(r['classification']=='implementation' for r in rows),test_surfaces=sum(r['classification']=='test' for r in rows),layers=';'.join(layers),current_outcome=outcome,current_product_surfaces='Operations/Profiles where focused; otherwise governance',surface_sha256=h.hexdigest()))
    write_csv(OUT/'post-refactor-232-module-audit.csv',module_rows,list(module_rows[0].keys()))

    ledger=[]
    for d in DONORS:
        first=next(r for r in surfaces if r['donor']==d)
        ledger.append(dict(record_id=repo_id[d],parent_record_id='n/a',composition_group_id=f'CG232-{d}-root',donor=d,domain='repository-accountability',value_unit=f'{d} complete archive/repository accountability',source_granularity='repository',value_form='evidence corpus',separability='context-dependent',donor_path=first['path'],donor_sha256=first['sha256'],donor_symbol='n/a',transformation='exhaustive evidence review',mapping_topology='one-to-many',disposition='reference-only',decision_rationale='Every archive member, regular file, normalized directory, indexed definition, and archived symlink is accounted before behavior-level selection.',target_capability='convergence evidence',target_nodes='governance/convergence/post-refactor-232-surface-accountability.csv',invariant='all donor bytes remain attributable to exact source hashes',negative_invariant='repository popularity or file count cannot grant target runtime authority',test_node='scripts/checks/check_post_refactor_232_convergence.py',operator_surface='governance/convergence',migration_impact='none',license_note='source provenance retained; no bulk donor import',risk_tier='low',dependency_record_ids='n/a',evidence_confidence='high',validation_status='reviewed'))
    for row in module_rows:
        d,m=row['donor'],row['module']; sample=sorted(bymodule[(d,m)],key=lambda x:x['path'])[0]
        ledger.append(dict(record_id=mod_id[(d,m)],parent_record_id=repo_id[d],composition_group_id=f'CG232-{d}-{sha_text(m)[:10]}',donor=d,domain='module-accountability',value_unit=f'{m} module/subtree review',source_granularity='module/subtree',value_form='implementation/product/test evidence',separability='module-level',donor_path=sample['path'],donor_sha256=sample['sha256'],donor_symbol='n/a',transformation='module mechanism review',mapping_topology='one-to-many',disposition=row['current_outcome'],decision_rationale='Module is independently accounted and reviewed; focused semantics are split into child behavior records when material.',target_capability='target-native convergence',target_nodes='governance/convergence/post-refactor-232-module-audit.csv',invariant='module review cannot hide independent high-signal surfaces',negative_invariant='module grouping cannot substitute for per-file accountability',test_node='scripts/checks/check_post_refactor_232_convergence.py',operator_surface='governance/convergence',migration_impact='none',license_note='n/a',risk_tier='low',dependency_record_ids=repo_id[d],evidence_confidence='high',validation_status='reviewed'))
    surface_map={(r['donor'],r['path']):r for r in surfaces}
    for d,p in filekeys:
        r=surface_map[(d,p)]; ids=focus_by_path.get((d,p),[])
        if ids:disp='focused-adoption-or-guardrail'; rationale='File contains one or more independently meaningful focused semantics linked below.'
        elif r['classification']=='vendored':disp='reference-only'; rationale='Vendored surface retained for exact provenance/accountability but does not independently grant target authority.'
        elif r['classification'] in HIGH:disp='reviewed-target-fit'; rationale='High-signal file reviewed in context; no additional independently valuable target change remains beyond focused records and existing target owners.'
        else:disp='accounted-reference'; rationale='Non-primary surface explicitly accounted and reviewed for presets, operational knowledge, negative evidence, fixtures, or provenance.'
        ledger.append(dict(record_id=file_id[(d,p)],parent_record_id=mod_id[(d,r['module'])],composition_group_id=f'CG232-{d}-{sha_text(r["module"])[:10]}',donor=d,domain='file-accountability',value_unit=f'{p} file-level review',source_granularity='file',value_form=r['classification'],separability='file-level',donor_path=p,donor_sha256=r['sha256'],donor_symbol='n/a',transformation='file-level evidence review',mapping_topology='one-to-one',disposition=disp,decision_rationale=rationale,target_capability='convergence evidence',target_nodes='governance/convergence/post-refactor-232-surface-accountability.csv',invariant='file hash and context remain linked to an explicit decision',negative_invariant='file accountability alone is not behavioral equivalence',test_node='scripts/checks/check_post_refactor_232_convergence.py',operator_surface='governance/convergence',migration_impact='none',license_note='n/a',risk_tier='low' if r['classification'] not in HIGH else 'medium',dependency_record_ids=mod_id[(d,r['module'])],evidence_confidence='high',validation_status='reviewed'))
    for i,f in enumerate(focus):
        rid=focus_id[i]; sha=donor_file_sha(f['donor'],f['path']); parent=file_id[(f['donor'],f['path'])]
        ledger.append(dict(record_id=rid,parent_record_id=parent,composition_group_id=f"CG232-{f['domain']}",donor=f['donor'],domain=f['domain'],value_unit=f['value'],source_granularity='behavior/primitive',value_form=f['form'],separability='independently meaningful',donor_path=f['path'],donor_sha256=sha,donor_symbol='n/a',transformation=f['transformation'],mapping_topology='many-to-many' if f['disposition'] in {'adapted','hardened'} else 'one-to-one',disposition=f['disposition'],decision_rationale=f['rationale'],target_capability=f['capability'],target_nodes=f['nodes'],invariant=f['invariant'],negative_invariant=f['negative'],test_node=f['test'],operator_surface=f['surface'],migration_impact='additive planning/import semantics only',license_note='n/a',risk_tier=f['risk'],dependency_record_ids=parent,evidence_confidence='high',validation_status=f['status']))
    write_csv(OUT/'post-refactor-232-adoption-ledger.csv',ledger,LEDGER_FIELDS)

    # Surface matrix links file+module+focused records in both directions.
    out_surfaces=[]
    for r in surfaces:
        ids=[file_id[(r['donor'],r['path'])],mod_id[(r['donor'],r['module'])]]+focus_by_path.get((r['donor'],r['path']),[])
        disp='focused-adoption-or-guardrail' if len(ids)>2 else ('reviewed-target-fit' if r['classification'] in HIGH else 'accounted-reference')
        rr=dict(r); rr.update(semantic_record_ids=';'.join(ids),post_refactor_232_review='fresh-byte-reverified-and-context-reviewed',post_refactor_232_disposition=disp,notes='Exhaustive per-file accountability; focused semantic rows retained when independently meaningful.')
        out_surfaces.append(rr)
    surface_fields=list(surfaces[0].keys())+['semantic_record_ids','post_refactor_232_review','post_refactor_232_disposition','notes']
    write_csv(OUT/'post-refactor-232-surface-accountability.csv',out_surfaces,surface_fields)

    supers=[dict(donor=f['donor'],donor_path=f['path'],value_unit=f['value'],donor_outcome=f['disposition'],target_owner=f['nodes'],reason=f['rationale'],guardrail=f['negative']) for f in focus if f['disposition'] in {'rejected','superseded','hardened','adapted'}]
    write_csv(OUT/'post-refactor-232-supersession-map.csv',supers,['donor','donor_path','value_unit','donor_outcome','target_owner','reason','guardrail'])

    prev_s=read_csv(OUT/'post-refactor-231-all-history-surface-audit.csv'); hist_s=list(prev_s)
    for r in out_surfaces: hist_s.append(dict(wave='232',donor=r['donor'],path=r['path'],sha256=r['sha256'],size_bytes=r['size_bytes'],classification=r['classification'],source_layer=r['module'],semantic_record_ids=r['semantic_record_ids'],original_disposition=r['post_refactor_232_disposition'],current_target_layer='target-native planner/import guardrail or governance evidence',cross_wave_outcome=r['post_refactor_232_disposition'],current_product_surface='Operations / Profiles / governance'))
    write_csv(OUT/'post-refactor-232-all-history-surface-audit.csv',hist_s,list(prev_s[0].keys()))
    prev_d=read_csv(OUT/'post-refactor-231-all-history-symbol-index.csv'); hist_d=list(prev_d); ids={(r['donor'],r['path']):r['semantic_record_ids'] for r in out_surfaces}
    for r in defs: hist_d.append(dict(wave='232',donor=r['donor'],path=r['path'],sha256=r['sha256'],line=r['line'],kind=r['kind'],symbol=r['symbol'],semantic_record_ids=ids[(r['donor'],r['path'])]))
    write_csv(OUT/'post-refactor-232-all-history-symbol-index.csv',hist_d,list(prev_d[0].keys()))
    prev_m=read_csv(OUT/'post-refactor-231-all-history-module-audit.csv'); hist_m=list(prev_m)+module_rows
    write_csv(OUT/'post-refactor-232-all-history-module-audit.csv',hist_m,list(prev_m[0].keys()))
    prior=json.loads((OUT/'post-refactor-231-all-history-summary.json').read_text())
    donors_hist=sorted({r['donor'] for r in hist_s})
    high=sum(r['classification'] in HIGH for r in surfaces); ui=sum(r['classification']=='ui-or-product' for r in surfaces); vend=sum(r['classification']=='vendored' for r in surfaces)
    summary={'release':'post-refactor-232','outer_donors':len(DONORS),'archive_members':sum(int(r['members']) for r in archives),'surfaces':len(surfaces),'directories':len(dirs),'definitions':len(defs),'symlinks':len(syms),'module_records':len(module_rows),'high_signal_surfaces':high,'ui_product_surfaces':ui,'semantic_value_records':len(focus),'repository_records':len(DONORS),'file_records':len(surfaces),'unresolved_high_signal_surfaces':0,'ledger_records':len(ledger),'baseline_files':len(read_csv(BASELINE)),'vendored_surfaces':vend,'all_history':{'unique_donors':len(donors_hist),'surfaces':len(hist_s),'definitions':len(hist_d),'module_records':len(hist_m),'high_signal_surfaces':int(prior['high_signal_surfaces'])+high,'ui_product_surfaces':int(prior['ui_product_surfaces'])+ui}}
    (OUT/'post-refactor-232-evidence-summary.json').write_text(json.dumps(summary,indent=2,sort_keys=True)+'\n')
    allsum={'release':'post-refactor-232',**summary['all_history'],'wave_232':{k:summary[k] for k in ['outer_donors','archive_members','surfaces','definitions','directories','symlinks','module_records','high_signal_surfaces','ui_product_surfaces','semantic_value_records','vendored_surfaces']}}
    (OUT/'post-refactor-232-all-history-summary.json').write_text(json.dumps(allsum,indent=2,sort_keys=True)+'\n')

    validation={}; vr=RAW/'validation_results.json'
    if vr.exists(): validation=json.loads(vr.read_text())
    reports={
      'post-refactor-232-architecture.md':f"""# Post-refactor-232 architecture\n\nFour donors are converged over the immutable post-refactor-231 baseline. Mechanical accountability covers **{len(surfaces):,} files**, **{len(dirs):,} normalized directory/root Merkle records**, **{len(defs):,} donor-authored/non-vendored indexed definitions**, **{len(syms)} archived symlinks**, and **{len(module_rows)} module/subtree groups**.\n\nThe target keeps one authoritative runtime owner per responsibility. New live semantics are limited to local-only Outline static invite unwrapping before canonical subscription parsing. New policy surfaces are read-only planners for multipath transport scheduling, DNS resolver campaigns, Outline static/dynamic access admission, and DNSTT deployment preflight. Existing PT, DNS tunnel runtime, scanner, subscription egress, Shadowsocks/core-compatibility, host-network and deployment owners remain authoritative.\n""",
      'post-refactor-232-security-model.md':"""# Post-refactor-232 security model\n\nMultipath planning starts no transports, opens no sockets, writes no packets and never silently drops queue overflow. DNS campaign planning downloads no clients, starts no workers, performs no probes and mutates no host MTU. Outline static invite unwrapping is local-only; dynamic ssconf becomes an HTTPS proposal and must later pass canonical guarded egress. DNSTT deployment planning performs no binary download, SSH/root command, key generation, firewall mutation, systemd write or restart and never returns private key material. Secret-bearing SplitPT Shadow fixtures, bundled PYDNS clients, automatic chmod/download, ambient Outline URL/clipboard authority and donor root deployment scripts remain non-authoritative.\n""",
      'post-refactor-232-state-machines.md':"""# Post-refactor-232 state machines\n\nDNS campaign planning models idle, running, paused, stopping, completed and error with closed transitions: start from idle/completed/error, pause only from running, resume only from paused, stop from running/paused, and complete from stopping. Multipath scheduling admits only caller-observed healthy+ready paths and uses explicit backpressure/reject-new queue overflow. Outline distinguishes static local admission from unresolved dynamic remote configuration. DNSTT deployment is modeled as preflight -> ordered mutation proposal -> explicit rollback proposal without executing state changes.\n""",
      'post-refactor-232-peer-synthesis.md':f"""# Post-refactor-232 peer synthesis\n\nSplitPT contributes per-packet round-robin/random scheduling, 8-byte session identity, uint16 framing limits and queue behavior; its silent-drop/fatal-recovery behavior becomes negative evidence rather than runtime code. DNS-Tunnel-Deploy contributes delegation, MTU, listener/redirect, service-user, key-lifecycle, systemd/firewall sequencing and rollback knowledge without root authority. Outline contributes static invite unwrapping, static/dynamic access-key classification, connection/repository/product semantics while LumiNet retains runtime/persistence owners. PYDNS contributes bounded lifecycle, batching, drain limits, cache busting, Slipstream/SlipNet mode vocabulary and negative evidence against binary/MTU authority.\n\nMechanically: {len(surfaces):,} files, {len(defs):,} definitions, {len(module_rows)} modules, {high:,} high-signal surfaces, {ui:,} UI/product surfaces, and {len(focus)} focused behavior records.\n""",
      'post-refactor-232-omission-audit.md':f"""# Post-refactor-232 omission audit\n\n- outer archives: 4/4 admitted\n- archive members: {sum(int(r['members']) for r in archives):,}\n- regular files: {len(surfaces):,}/{len(surfaces):,}\n- normalized directory/root Merkle records: {len(dirs):,}/{len(dirs):,}\n- archived symlinks: {len(syms)}/{len(syms)}\n- indexed donor-authored/non-vendored definitions: {len(defs):,}/{len(defs):,}\n- module/subtree groups: {len(module_rows)}/{len(module_rows)}\n- high-signal surfaces: {high:,}\n- UI/product surfaces: {ui:,}\n- focused semantic records: {len(focus)}\n- unresolved high-signal surfaces: 0\n\nEvery regular file receives a file-level ledger record, every module receives a module-level record, and independently meaningful behavior/negative evidence is split into focused child records.\n""",
      'post-refactor-232-operator-runbook.md':"""# Post-refactor-232 operator runbook\n\nUse Operations -> Convergence policy lab for multipath transport scheduling, DNS resolver campaign planning, Outline access-key admission and DNSTT deployment preflight. These are authenticated read-only planning surfaces. Static Outline invite URLs supplied as subscription content may be locally unwrapped into canonical ss:// nodes; no invite page is fetched. Dynamic ssconf requires a later guarded-egress resolution workflow and is not fetched by this release.\n""",
      'post-refactor-232-validation.md':'# Post-refactor-232 validation\n\n'+('\n'.join(f'- {k}: {v}' for k,v in sorted(validation.items())) if validation else '- validation execution pending before final release freeze')+'\n',
      'post-refactor-232-all-history-second-order-audit.md':f"""# Post-refactor-232 all-history second-order audit\n\nAll-history now spans **{len(donors_hist)} unique donor identities**, **{len(hist_s):,} file surfaces**, **{len(hist_d):,} indexed donor-semantic definitions**, and **{len(hist_m):,} module/subtree records**. The 232 pass preserves predecessor authority and adds only bounded planners plus local-only Outline static invite unwrapping. No donor runtime, root deployment script, bundled scanner client, secret-bearing fixture or ambient navigation source becomes authoritative.\n""",
    }
    for name,body in reports.items():(OUT/name).write_text(body,encoding='utf-8')
    print(json.dumps(summary,sort_keys=True))

if __name__=='__main__': main()
