/* Generated by cbindgen - DO NOT EDIT */

#ifndef LUMICORE_H
#define LUMICORE_H

/* Warning: this file is autogenously generated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * DNS A record (IPv4 address).
 */
#define LumiTYPE_A 1

/**
 * DNS NS record (authoritative name server).
 */
#define LumiTYPE_NS 2

/**
 * DNS CNAME record (canonical name alias).
 */
#define LumiTYPE_CNAME 5

/**
 * DNS SOA record (start of authority).
 */
#define LumiTYPE_SOA 6

/**
 * DNS PTR record (pointer / reverse lookup).
 */
#define LumiTYPE_PTR 12

/**
 * DNS MX record (mail exchange).
 */
#define LumiTYPE_MX 15

/**
 * DNS TXT record (text).
 */
#define LumiTYPE_TXT 16

/**
 * DNS AAAA record (IPv6 address).
 */
#define LumiTYPE_AAAA 28

/**
 * DNS HTTPS record (SVCB/HTTPS bindings).
 */
#define LumiTYPE_HTTPS 65

/**
 * DNS IN (Internet) class.
 */
#define LumiCLASS_IN 1

#define LumiLUMICORE_ABI_VERSION 3

#define LumiFFI_OK 0

#define LumiFFI_ERR_NULL -1

#define LumiFFI_ERR_PANIC -2

#define LumiFFI_ERR_ABI -3

#define LumiFFI_ERR_CAPACITY -4

#define LumiFFI_ERR_DECODE -5

#define LumiABI_MAJOR 3

#define LumiABI_MINOR 0

#define LumiABI_PATCH 0

#define LumiSTREAM_EVT_PROBE_RESULT 1

#define LumiSTREAM_EVT_POOL_UPDATE 2

#define LumiSTREAM_EVT_SCAN_DONE 3

#define LumiSTREAM_EVT_ERROR 255

#define LumiECH_EXT_TYPE 65037

/**
 * Probe result — matching PackedResult in binary_scan.go C block
 */
typedef struct LumiPackedResult LumiPackedResult;

/**
 * Packed scan configuration — matching PackedScanConfig in binary_scan.go C block
 */
typedef struct LumiPackedScanConfig LumiPackedScanConfig;

/**
 * Packed scan target — matching PackedTarget in binary_scan.go C block
 */
typedef struct LumiPackedTarget LumiPackedTarget;

typedef struct LumiFfiStatus {
    int32_t code;
    uintptr_t output_len;
    uint16_t error_code;
    uint16_t reserved;
} LumiFfiStatus;

typedef struct LumiFfiEnvelope {
    uint16_t abi_version;
    uint16_t op_code;
    uint32_t flags;
    uint64_t trace_id_hi;
    uint64_t trace_id_lo;
    uintptr_t input_len;
    uintptr_t output_cap;
} LumiFfiEnvelope;

typedef struct LumiStreamHandle {
    uint64_t stream_id;
    uint64_t reserved;
} LumiStreamHandle;

typedef void (*LumiStreamCallback)(uint16_t event_type,
                                   const uint8_t *data,
                                   uintptr_t data_len,
                                   void *user_data);

/**
 * Called by the OS loader (or explicitly by Go) to initialise Rust globals.
 * Must be called before any other lumicore_* function.
 */
void lumicore_init(void);

/**
 * Called on process shutdown. Gives runtime a chance to flush logs.
 */
void lumicore_shutdown(void);

/**
 * Frees a string that was allocated by Rust and passed to C.
 *
 * # Safety
 * This function must only be called with a pointer returned by Rust FFI.
 */
void free_string(char *ptr);

/**
 * FFI entry point for binary scan execution.
 */
struct LumiFfiStatus lumicore_scan_execution(const struct LumiFfiEnvelope *envelope,
                                             const struct LumiPackedScanConfig *config,
                                             const struct LumiPackedTarget *targets,
                                             uintptr_t target_len,
                                             struct LumiPackedResult *out_results);

/**
 * Wrapper for ICMP scanning.
 *
 * Input JSON: `{"targets": ["192.168.1.1"], "config": <ScanConfig>}`
 * Output JSON: `{"results": [<ProbeResult>]}`
 */
char *scan_icmp_ffi(const char *input_json);

/**
 * Wrapper for TCP probing.
 *
 * Input JSON: `{"target": "127.0.0.1", "port": 80, "timeout_ms": 1000}`
 */
char *probe_tcp_ffi(const char *input_json);

/**
 * Wrapper for Port scanning.
 *
 * Input JSON: `{"target": "127.0.0.1", "ports": [80, 443], "config": <ScanConfig>}`
 */
char *scan_ports_ffi(const char *input_json);

/**
 * Wrapper for DNS scanning.
 *
 * Input JSON: `{"server": "8.8.8.8", "domain": "example.com", "record_type": "A", "protocol": "udp", "timeout_ms": 3000}`
 */
char *scan_dns_ffi(const char *input_json);

/**
 * Wrapper for TLS probing.
 *
 * Input JSON: `{"target": "example.com", "port": 443, "timeout_ms": 2000}`
 */
char *probe_tls_ffi(const char *input_json);

/**
 * Wrapper for SOCKS5 probing.
 *
 * Input JSON: `{"proxy_addr": "127.0.0.1:1080", "target": "example.com:80", "timeout_ms": 2000}`
 */
char *probe_socks5_ffi(const char *input_json);

/**
 * Wrapper for HTTP client probing.
 *
 * Input JSON: `{"url": "http://example.com", "timeout_ms": 2000, "proxy": null}`
 */
char *probe_http_ffi(const char *input_json);

/**
 * Wrapper for SNI detection.
 *
 * Input JSON: `{"domain": "blocked.com", "timeout_ms": 2000}`
 */
char *detect_sni_ffi(const char *input_json);

/**
 * Wrapper for Speed testing.
 *
 * Input JSON: `{"server_url": "http://speedtest.example.com", "timeout_ms": 5000}`
 */
char *test_speed_ffi(const char *input_json);

/**
 * Wrapper for CIDR expansion.
 *
 * Input JSON: `{"cidr": "192.168.1.0/24"}`
 */
char *expand_cidr_ffi(const char *input_json);

/**
 * Wrapper for WireGuard probing.
 *
 * Input JSON: `{"ip": "10.0.0.1", "port": 51820, "timeout_ms": 2000}`
 */
char *probe_wg_ffi(const char *input_json);

/**
 * Wrapper for captive portal detection.
 *
 * Input JSON: `{"timeout_ms": 3000}`
 */
char *detect_captive_portal_ffi(const char *input_json);

/**
 * Wrapper for ClientHello padding.
 *
 * Input JSON: `{"raw_hex": "160301...", "pad_len": 500}`
 */
char *pad_client_hello_ffi(const char *input_json);

/**
 * Wrapper for raw fake TCP packet injection.
 *
 * Input JSON: `{"target_ip": "192.0.2.1", "port": 443, "ttl": 4, "flags": 24, "payload_hex": "160301..."}`
 */
char *inject_fake_packet_ffi(const char *input_json);

/**
 * Initializes the shared memory packet channel.
 *
 * Accepts the raw pointer to the mapped memory and its size.
 */
int32_t init_shm_ffi(void *addr, uintptr_t size);

/**
 * Helper FFI to push a packet to Go.
 */
int32_t push_packet_ffi(const uint8_t *data, uint32_t len);

/**
 * Helper FFI to pop a packet from Go.
 * Returns the length of the popped packet, or 0 if empty.
 * Copies the packet into buffer up to max_len.
 */
int32_t pop_packet_ffi(uint8_t *buf, uint32_t max_len);

/**
 * Disassembles custom raw network payload bytes using Capstone.
 */
char *disassemble_shellcode_ffi(const char *input_json);

/**
 * Primary FFI entry point. Called from Go via CGo.
 * Layout: input = FfiEnvelope (36 bytes) | payload (env.input_len bytes)
 */
struct LumiFfiStatus lumicore_call(const struct LumiFfiEnvelope *env,
                                   const uint8_t *input,
                                   uint8_t *output);

/**
 * Returns packed u64: bits[47:32]=major, bits[31:16]=minor, bits[15:0]=patch.
 * Returns 0 if the library is older than minimum_required_major.
 */
uint64_t lumicore_version(uint16_t minimum_required_major);

/**
 * Writes "lumicore/3.0.0" into buf. Returns bytes written. Thread-safe.
 */
uintptr_t lumicore_version_string(uint8_t *buf, uintptr_t buf_len);

struct LumiStreamHandle lumicore_stream_start(uint16_t op,
                                              const uint8_t *input,
                                              uintptr_t input_len,
                                              LumiStreamCallback cb,
                                              void *user_data);

void lumicore_stream_cancel(struct LumiStreamHandle handle);

#endif  /* LUMICORE_H */
