package mobilecore

import "github.com/maybeknott/luminet/internal/runtime/proxy"

// DefaultConfig returns the gobind-facing configuration with the same
// evasion defaults as every other transport adapter. Mobile-only location and
// parsed outbound fields remain zero until supplied by the mobile host.
func DefaultConfig() MobileConfig {
	return ConfigFromEvasion(proxy.DefaultEvasionConfig())
}

// ConfigFromEvasion translates canonical evasion state into the
// gobind JSON shape. Callers decide whether the source config must be redacted.
func ConfigFromEvasion(cfg proxy.EvasionConfig) MobileConfig {
	return MobileConfig{
		Port:                    cfg.Port,
		SplitBytes:              cfg.SplitBytes,
		DelayMs:                 cfg.DelayMs,
		MutateHost:              cfg.MutateHost,
		MutateHeaderSpace:       cfg.MutateHeaderSpace,
		AutoSni:                 cfg.AutoSni,
		PrecisionSniSplits:      cfg.PrecisionSniSplits,
		SniSplitOffset:          cfg.SniSplitOffset,
		Packets:                 cfg.Packets,
		MinLength:               cfg.MinLength,
		MaxLength:               cfg.MaxLength,
		TlsRecordSplit:          cfg.TlsRecordSplit,
		DnsResolver:             cfg.DnsResolver,
		DnsForwarderPort:        cfg.DnsForwarderPort,
		DnsForwarderEnabled:     cfg.DnsForwarderEnabled,
		SystemProxyEnabled:      cfg.SystemProxyEnabled,
		SniSpoof:                cfg.SniSpoof,
		ClientHelloPadding:      cfg.ClientHelloPadding,
		DelayJitter:             cfg.DelayJitter,
		TcpWindowClamp:          cfg.TcpWindowClamp,
		CustomUserAgent:         cfg.CustomUserAgent,
		CovertMode:              cfg.CovertMode,
		CovertServerlessUrl:     cfg.CovertServerlessUrl,
		CovertDnsDomain:         cfg.CovertDnsDomain,
		CovertGsaUrl:            cfg.CovertGsaUrl,
		CovertGsaKey:            cfg.CovertGsaKey,
		CovertGdocsFolderId:     cfg.CovertGdocsFolderId,
		CovertGdocsAccessToken:  cfg.CovertGdocsAccessToken,
		CovertCfg:               cfg.CovertCfg,
		FakePacketInject:        cfg.FakePacketInject,
		FakePacketTtl:           cfg.FakePacketTtl,
		MutateSniCase:           cfg.MutateSniCase,
		MutateMethod:            cfg.MutateMethod,
		MutateAbsoluteUri:       cfg.MutateAbsoluteUri,
		HttpPadding:             cfg.HttpPadding,
		PreflightSignature:      cfg.PreflightSignature,
		PreflightDelayMs:        cfg.PreflightDelayMs,
		SessionFrag:             cfg.SessionFrag,
		SessionFragProb:         cfg.SessionFragProb,
		SessionFragMinTotal:     cfg.SessionFragMinTotal,
		SessionFragMaxTotal:     cfg.SessionFragMaxTotal,
		SessionFragMinChunk:     cfg.SessionFragMinChunk,
		SessionFragMaxChunk:     cfg.SessionFragMaxChunk,
		SessionFragMinDelayMs:   cfg.SessionFragMinDelayMs,
		SessionFragMaxDelayMs:   cfg.SessionFragMaxDelayMs,
		IpSpoofingEnabled:       cfg.IpSpoofingEnabled,
		IpSpoofingDecoyIP:       cfg.IpSpoofingDecoyIP,
		IpSpoofingDstReal:       cfg.IpSpoofingDstReal,
		OutOfWindowEnabled:      cfg.OutOfWindowEnabled,
		OutOfWindowSeqOffset:    cfg.OutOfWindowSeqOffset,
		DecoySniPool:            cfg.DecoySniPool,
		OobEnabled:              cfg.OobEnabled,
		OobexEnabled:            cfg.OobexEnabled,
		AsyncReactorEnabled:     cfg.AsyncReactorEnabled,
		LossRate:                cfg.LossRate,
		EmulatedLatency:         cfg.EmulatedLatency,
		EmulatedJitter:          cfg.EmulatedJitter,
		CircularCacheCap:        cfg.CircularCacheCap,
		RandomMultiSplit:        cfg.RandomMultiSplit,
		NumFragments:            cfg.NumFragments,
		ShaperReadRate:          cfg.ShaperReadRate,
		ShaperWriteRate:         cfg.ShaperWriteRate,
		CovertSocketProtectPath: cfg.CovertSocketProtectPath,
		MobileAssetsEnabled:     cfg.MobileAssetsEnabled,
		ZygiskHideEnabled:       cfg.ZygiskHideEnabled,
		HardenedTlsEnabled:      cfg.HardenedTlsEnabled,
		UpgenEnabled:            cfg.UpgenEnabled,
		UpgenSeedHex:            cfg.UpgenSeedHex,
		UpgenEntropyMatch:       cfg.UpgenEntropyMatch,
		UpgenQuicExhaustionRate: cfg.UpgenQuicExhaustionRate,
		StegoEnabled:            cfg.StegoEnabled,
		StegoMode:               cfg.StegoMode,
		StegoDecoyImagePath:     cfg.StegoDecoyImagePath,
		StegoWebRTCSDPSpoof:     cfg.StegoWebRTCSDPSpoof,
		HostsOverride:           cfg.HostsOverride,
		ResidentialCloaking:     cfg.ResidentialCloaking,
		ResidentialEgressNode:   cfg.ResidentialEgressNode,
		MssClampingValue:        cfg.MssClampingValue,
		DnsLeaksShield:          cfg.DnsLeaksShield,
		MssPreset:               cfg.MssPreset,
		ShadowsocksPrefix:       cfg.ShadowsocksPrefix,
		AutoReconnectEnabled:    cfg.AutoReconnectEnabled,
		AutoReconnectMaxTries:   cfg.AutoReconnectMaxTries,
		AutoReconnectDelayMs:    cfg.AutoReconnectDelayMs,
	}
}

// ConfigToEvasion translates the mobile wire shape into the
// canonical evasion intent. Mobile-only sensor and outbound-parser fields do
// not belong to evasion runtime state and are deliberately excluded.
func ConfigToEvasion(cfg MobileConfig) proxy.EvasionConfig {
	return proxy.EvasionConfig{
		Port:                    cfg.Port,
		SplitBytes:              cfg.SplitBytes,
		DelayMs:                 cfg.DelayMs,
		MutateHost:              cfg.MutateHost,
		MutateHeaderSpace:       cfg.MutateHeaderSpace,
		AutoSni:                 cfg.AutoSni,
		PrecisionSniSplits:      cfg.PrecisionSniSplits,
		SniSplitOffset:          cfg.SniSplitOffset,
		Packets:                 cfg.Packets,
		MinLength:               cfg.MinLength,
		MaxLength:               cfg.MaxLength,
		TlsRecordSplit:          cfg.TlsRecordSplit,
		DnsResolver:             cfg.DnsResolver,
		DnsForwarderPort:        cfg.DnsForwarderPort,
		DnsForwarderEnabled:     cfg.DnsForwarderEnabled,
		SystemProxyEnabled:      cfg.SystemProxyEnabled,
		SniSpoof:                cfg.SniSpoof,
		ClientHelloPadding:      cfg.ClientHelloPadding,
		DelayJitter:             cfg.DelayJitter,
		TcpWindowClamp:          cfg.TcpWindowClamp,
		CustomUserAgent:         cfg.CustomUserAgent,
		CovertMode:              cfg.CovertMode,
		CovertServerlessUrl:     cfg.CovertServerlessUrl,
		CovertDnsDomain:         cfg.CovertDnsDomain,
		CovertGsaUrl:            cfg.CovertGsaUrl,
		CovertGsaKey:            cfg.CovertGsaKey,
		CovertGdocsFolderId:     cfg.CovertGdocsFolderId,
		CovertGdocsAccessToken:  cfg.CovertGdocsAccessToken,
		CovertCfg:               cfg.CovertCfg,
		FakePacketInject:        cfg.FakePacketInject,
		FakePacketTtl:           cfg.FakePacketTtl,
		MutateSniCase:           cfg.MutateSniCase,
		MutateMethod:            cfg.MutateMethod,
		MutateAbsoluteUri:       cfg.MutateAbsoluteUri,
		HttpPadding:             cfg.HttpPadding,
		PreflightSignature:      cfg.PreflightSignature,
		PreflightDelayMs:        cfg.PreflightDelayMs,
		SessionFrag:             cfg.SessionFrag,
		SessionFragProb:         cfg.SessionFragProb,
		SessionFragMinTotal:     cfg.SessionFragMinTotal,
		SessionFragMaxTotal:     cfg.SessionFragMaxTotal,
		SessionFragMinChunk:     cfg.SessionFragMinChunk,
		SessionFragMaxChunk:     cfg.SessionFragMaxChunk,
		SessionFragMinDelayMs:   cfg.SessionFragMinDelayMs,
		SessionFragMaxDelayMs:   cfg.SessionFragMaxDelayMs,
		IpSpoofingEnabled:       cfg.IpSpoofingEnabled,
		IpSpoofingDecoyIP:       cfg.IpSpoofingDecoyIP,
		IpSpoofingDstReal:       cfg.IpSpoofingDstReal,
		OutOfWindowEnabled:      cfg.OutOfWindowEnabled,
		OutOfWindowSeqOffset:    cfg.OutOfWindowSeqOffset,
		DecoySniPool:            cfg.DecoySniPool,
		OobEnabled:              cfg.OobEnabled,
		OobexEnabled:            cfg.OobexEnabled,
		AsyncReactorEnabled:     cfg.AsyncReactorEnabled,
		LossRate:                cfg.LossRate,
		EmulatedLatency:         cfg.EmulatedLatency,
		EmulatedJitter:          cfg.EmulatedJitter,
		CircularCacheCap:        cfg.CircularCacheCap,
		RandomMultiSplit:        cfg.RandomMultiSplit,
		NumFragments:            cfg.NumFragments,
		ShaperReadRate:          cfg.ShaperReadRate,
		ShaperWriteRate:         cfg.ShaperWriteRate,
		CovertSocketProtectPath: cfg.CovertSocketProtectPath,
		MobileAssetsEnabled:     cfg.MobileAssetsEnabled,
		ZygiskHideEnabled:       cfg.ZygiskHideEnabled,
		HardenedTlsEnabled:      cfg.HardenedTlsEnabled,
		UpgenEnabled:            cfg.UpgenEnabled,
		UpgenSeedHex:            cfg.UpgenSeedHex,
		UpgenEntropyMatch:       cfg.UpgenEntropyMatch,
		UpgenQuicExhaustionRate: cfg.UpgenQuicExhaustionRate,
		StegoEnabled:            cfg.StegoEnabled,
		StegoMode:               cfg.StegoMode,
		StegoDecoyImagePath:     cfg.StegoDecoyImagePath,
		StegoWebRTCSDPSpoof:     cfg.StegoWebRTCSDPSpoof,
		HostsOverride:           cfg.HostsOverride,
		ResidentialCloaking:     cfg.ResidentialCloaking,
		ResidentialEgressNode:   cfg.ResidentialEgressNode,
		MssClampingValue:        cfg.MssClampingValue,
		DnsLeaksShield:          cfg.DnsLeaksShield,
		MssPreset:               cfg.MssPreset,
		ShadowsocksPrefix:       cfg.ShadowsocksPrefix,
		AutoReconnectEnabled:    cfg.AutoReconnectEnabled,
		AutoReconnectMaxTries:   cfg.AutoReconnectMaxTries,
		AutoReconnectDelayMs:    cfg.AutoReconnectDelayMs,
	}
}
