//! Privoxy Action File Synthesizer
//!
//! Converts domain blacklist and proxy rules into Privoxy `.action` file format
//! using `{+forward-override{forward-socks5 ...}}` and direct bypass specifications.

use std::collections::BTreeSet;

pub struct PrivoxyActionGenerator {
    pub socks5_proxy: String,
    forward_domains: BTreeSet<String>,
    direct_bypass_domains: BTreeSet<String>,
}

impl PrivoxyActionGenerator {
    pub fn new(socks5_endpoint: impl Into<String>) -> Self {
        Self {
            socks5_proxy: socks5_endpoint.into(),
            forward_domains: BTreeSet::new(),
            direct_bypass_domains: BTreeSet::new(),
        }
    }

    pub fn add_forward_domain(&mut self, domain: &str) {
        let cleaned = domain.trim().trim_end_matches('.').to_lowercase();
        if !cleaned.is_empty() {
            self.forward_domains.insert(cleaned);
        }
    }

    pub fn add_direct_bypass(&mut self, domain: &str) {
        let cleaned = domain.trim().trim_end_matches('.').to_lowercase();
        if !cleaned.is_empty() {
            self.direct_bypass_domains.insert(cleaned);
        }
    }

    pub fn generate_action_file(&self) -> String {
        let mut out = String::new();
        out.push_str("# Automatically generated by LumiNet PrivoxyActionGenerator\n");
        out.push_str("# Direct forward bypass rules\n");
        out.push_str("{-forward-override}\n");
        for d in &self.direct_bypass_domains {
            if d.starts_with('.') {
                out.push_str(&format!("{}\n", d));
            } else {
                out.push_str(&format!(".{}\n", d));
            }
        }

        out.push('\n');
        out.push_str(&format!(
            "{{+forward-override{{forward-socks5 {} .}}}}\n",
            self.socks5_proxy
        ));
        for d in &self.forward_domains {
            if d.starts_with('.') {
                out.push_str(&format!("{}\n", d));
            } else {
                out.push_str(&format!(".{}\n", d));
            }
        }

        out
    }

    pub fn rule_counts(&self) -> (usize, usize) {
        (self.forward_domains.len(), self.direct_bypass_domains.len())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_privoxy_action_generation() {
        let mut gen = PrivoxyActionGenerator::new("127.0.0.1:10808");
        gen.add_forward_domain("google.com");
        gen.add_forward_domain("wikipedia.org");
        gen.add_direct_bypass("internal.corp");

        let content = gen.generate_action_file();
        assert!(content.contains("{-forward-override}"));
        assert!(content.contains(".internal.corp"));
        assert!(content.contains("{+forward-override{forward-socks5 127.0.0.1:10808 .}}"));
        assert!(content.contains(".google.com"));
        assert!(content.contains(".wikipedia.org"));
    }
}
