use std::net::IpAddr;

/// Represents the parsed rule sections for routing decisions.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ParsedRouteRules {
    pub block_rules: Vec<String>,
    pub direct_rules: Vec<String>,
}

/// Splits route configuration into [block] and [direct] sections.
/// Lines before any recognized header or under unrecognized headers are discarded (fail-closed).
pub fn split_sections(text: &str) -> (String, String) {
    let mut block = String::new();
    let mut direct = String::new();
    let mut current: Option<&mut String> = None;

    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let lowered = trimmed.to_lowercase();
        if lowered == "[block]" {
            current = Some(&mut block);
            continue;
        }
        if lowered == "[direct]" {
            current = Some(&mut direct);
            continue;
        }
        if lowered.starts_with('[') {
            current = None;
            continue;
        }
        if let Some(target) = current.as_deref_mut() {
            target.push_str(trimmed);
            target.push('\n');
        }
    }
    (block, direct)
}

/// Normalizes domain rules by trimming and stripping mihomo's `+.` subdomain prefix.
pub fn normalize_mihomo_domains(domains: &str) -> Vec<String> {
    domains
        .lines()
        .map(|line| line.trim())
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|line| line.strip_prefix("+.").unwrap_or(line).to_string())
        .collect()
}

/// Validates whether a CIDR string contains a valid IP address and valid prefix length.
pub fn validate_cidr(cidr: &str) -> bool {
    let parts: Vec<&str> = cidr.trim().split('/').collect();
    if parts.len() != 2 {
        return false;
    }
    let ip = match parts[0].parse::<IpAddr>() {
        Ok(addr) => addr,
        Err(_) => return false,
    };
    let prefix = match parts[1].parse::<u8>() {
        Ok(p) => p,
        Err(_) => return false,
    };
    match ip {
        IpAddr::V4(_) => prefix <= 32,
        IpAddr::V6(_) => prefix <= 128,
    }
}

/// Compiles a combined routing configuration document.
pub fn compile_combined_ruleset(
    user_routes: Option<&str>,
    bundled_domains: &str,
    bundled_ips: &str,
) -> String {
    let (user_block, user_direct) = match user_routes {
        Some(text) => split_sections(text),
        None => (String::new(), String::new()),
    };

    let normalized_domains = normalize_mihomo_domains(bundled_domains).join("\n");

    let mut out = String::new();
    out.push_str("# Generated by LumiNet Routing Engine.\n");
    out.push_str("[block]\n");
    if !user_block.is_empty() {
        out.push_str(&user_block);
    }
    out.push_str("[direct]\n");
    if !normalized_domains.is_empty() {
        out.push_str(&normalized_domains);
        out.push('\n');
    }
    if !bundled_ips.is_empty() {
        out.push_str(bundled_ips.trim());
        out.push('\n');
    }
    if !user_direct.is_empty() {
        out.push_str(&user_direct);
    }
    out
}

/// Validates whether an upstream protocol can be routed through a MASQUE / connect-ip tunnel.
/// Protocols like QUIC/Hysteria require initial datagrams >= 1280 bytes which exceed standard tunnel MTU.
pub fn unusable_behind_tunnel(kind: &str, carries_quic: bool) -> Option<String> {
    if carries_quic {
        return None;
    }
    match kind.to_ascii_lowercase().as_str() {
        "hysteria" | "hysteria2" | "tuic" => Some(format!(
            "{kind} operates over UDP/QUIC requiring minimum 1280-byte datagrams which exceed the inner MTU of MASQUE/connect-ip tunnels without WireGuard encapsulation"
        )),
        _ => None,
    }
}
