//! # RouterOS Firewall Rule & Address-List Exporter
//!
//! Generates MikroTik RouterOS scripts for address-list entries, routing marks,
//! and policy routing rules. Ported and enhanced from layerssss/gfwlist2routeos.

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RouterOsExportFormat {
    AddressList,
    StaticRoutes { gateway: String },
    MangleMark { routing_mark: String },
}

#[derive(Debug, Clone, Default)]
pub struct RouterOsRuleExporter {
    entries: Vec<String>,
}

impl RouterOsRuleExporter {
    pub fn new() -> Self {
        Self { entries: Vec::new() }
    }

    pub fn add_entry(&mut self, entry: &str) {
        let clean = entry.trim();
        if !clean.is_empty() && !clean.starts_with('#') {
            self.entries.push(clean.to_string());
        }
    }

    pub fn export_script(&self, list_name: &str, format: RouterOsExportFormat) -> String {
        let mut script = String::with_capacity(self.entries.len() * 64);
        script.push_str("# RouterOS Script generated by LumiNet\n");

        match format {
            RouterOsExportFormat::AddressList => {
                script.push_str("/ip firewall address-list\n");
                for entry in &self.entries {
                    script.push_str(&format!(
                        "add list={} address={} comment=\"LumiNet auto\"\n",
                        list_name, entry
                    ));
                }
            }
            RouterOsExportFormat::StaticRoutes { gateway } => {
                script.push_str("/ip route\n");
                for entry in &self.entries {
                    script.push_str(&format!(
                        "add dst-address={} gateway={} check-gateway=ping comment=\"LumiNet auto\"\n",
                        entry, gateway
                    ));
                }
            }
            RouterOsExportFormat::MangleMark { routing_mark } => {
                script.push_str("/ip firewall mangle\n");
                script.push_str(&format!(
                    "add chain=prerouting dst-address-list={} action=mark-routing new-routing-mark={} passthrough=yes comment=\"LumiNet bypass\"\n",
                    list_name, routing_mark
                ));
            }
        }

        script
    }

    pub fn entry_count(&self) -> usize {
        self.entries.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_routeros_address_list_export() {
        let mut exporter = RouterOsRuleExporter::new();
        exporter.add_entry("91.108.56.0/22");
        exporter.add_entry("149.154.160.0/20");

        let script = exporter.export_script("telegram", RouterOsExportFormat::AddressList);
        assert!(script.contains("/ip firewall address-list"));
        assert!(script.contains("add list=telegram address=91.108.56.0/22"));
    }

    #[test]
    fn test_routeros_mangle_export() {
        let exporter = RouterOsRuleExporter::new();
        let script = exporter.export_script(
            "gfwlist",
            RouterOsExportFormat::MangleMark {
                routing_mark: "vpn_traffic".to_string(),
            },
        );
        assert!(script.contains("action=mark-routing new-routing-mark=vpn_traffic"));
    }
}
