package proxyconfig

import (
	"fmt"
	"sort"
	"strings"
	"sync"
)

type PrivoxyActionGenerator struct {
	Socks5Proxy   string
	forwardDomain map[string]bool
	bypassDomain  map[string]bool
	mu            sync.Mutex
}

func NewPrivoxyActionGenerator(socks5Proxy string) *PrivoxyActionGenerator {
	return &PrivoxyActionGenerator{
		Socks5Proxy:   socks5Proxy,
		forwardDomain: make(map[string]bool),
		bypassDomain:  make(map[string]bool),
	}
}

func (g *PrivoxyActionGenerator) AddForwardDomain(domain string) {
	g.mu.Lock()
	defer g.mu.Unlock()
	clean := strings.Trim(strings.ToLower(domain), ". ")
	if clean != "" {
		g.forwardDomain[clean] = true
	}
}

func (g *PrivoxyActionGenerator) AddDirectBypass(domain string) {
	g.mu.Lock()
	defer g.mu.Unlock()
	clean := strings.Trim(strings.ToLower(domain), ". ")
	if clean != "" {
		g.bypassDomain[clean] = true
	}
}

func (g *PrivoxyActionGenerator) GenerateActionFile() string {
	g.mu.Lock()
	defer g.mu.Unlock()

	var sb strings.Builder
	sb.WriteString("# Generated by LumiNet PrivoxyActionGenerator\n")
	sb.WriteString("{-forward-override}\n")

	var bypass []string
	for d := range g.bypassDomain {
		bypass = append(bypass, d)
	}
	sort.Strings(bypass)
	for _, d := range bypass {
		sb.WriteString(fmt.Sprintf(".%s\n", d))
	}

	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("{+forward-override{forward-socks5 %s .}}\n", g.Socks5Proxy))

	var forward []string
	for d := range g.forwardDomain {
		forward = append(forward, d)
	}
	sort.Strings(forward)
	for _, d := range forward {
		sb.WriteString(fmt.Sprintf(".%s\n", d))
	}

	return sb.String()
}
