package mitm

// Deprecated source-compatibility aliases — canonical types in mitm_fronting_profile_manager.go
type MitmFrontingProfileManagerTuningHelper = MitmFrontingProfileManager
type MitmFrontingProfileCacheTuningHelper = MitmFrontingProfileCache
type MitmFrontingProfileDiagnosticsTuningHelper = MitmFrontingProfileDiagnostics
