package mitm

// Deprecated source-compatibility aliases — canonical types in mitm_fronting_profile_manager_diagnostics.go
type MitmFrontingProfileManagerDiagnosticsHelper = MitmFrontingProfileManagerDiagnostics
type MitmFrontingProfileCacheDiagnosticsHelper = MitmFrontingProfileCacheDiagnostics
type MitmFrontingProfileDiagnosticsDiagnosticsHelper = MitmFrontingProfileDiagnosticsDiagnostics
