package mitm

// Deprecated source-compatibility aliases — canonical types in mitm_fronting_socks_server.go
type MitmFrontingSocksServerTuningHelper = MitmFrontingSocksServer
type MitmFrontingHttpTunnelTuningHelper = MitmFrontingHttpTunnel
type MitmFrontingTunnelActiveStatusTuningHelper = MitmFrontingTunnelActiveStatus
