package mitm

// Deprecated source-compatibility aliases — canonical types in mitm_fronting_route_optimizer.go
type MitmFrontingRouteOptimizerTuningHelper = MitmFrontingRouteOptimizer
type MitmFrontingRouteHealthTuningHelper = MitmFrontingRouteHealth
type MitmFrontingRouteRegistryTuningHelper = MitmFrontingRouteRegistry
